export * from './course.service';
import { CourseService } from './course.service';
export * from './course-draft.service';
import { CourseDraftService } from './course-draft.service';
export * from './course-membership.service';
import { CourseMembershipService } from './course-membership.service';
export * from './file.service';
import { FileService } from './file.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './security.service';
import { SecurityService } from './security.service';
export * from './spring-doc-helper.service';
import { SpringDocHelperService } from './spring-doc-helper.service';
export * from './system-status.service';
import { SystemStatusService } from './system-status.service';
export * from './test.service';
import { TestService } from './test.service';
export * from './test-configuration.service';
import { TestConfigurationService } from './test-configuration.service';
export * from './test-draft.service';
import { TestDraftService } from './test-draft.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './websocket.service';
import { WebsocketService } from './websocket.service';
export const APIS = [CourseService, CourseDraftService, CourseMembershipService, FileService, GroupService, SecurityService, SpringDocHelperService, SystemStatusService, TestService, TestConfigurationService, TestDraftService, UserService, WebsocketService];
