/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestPublicationFeedback } from './test-publication-feedback';


export interface AnswerDraft { 
    key: string;
    createdAt: Date;
    updatedAt: Date;
    publishedAt?: Date;
    position: number;
    required?: boolean;
    correct?: boolean;
    title?: string;
    description?: string;
    content: string;
    publicationFeedback: Array<TestPublicationFeedback>;
}

