/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CourseStatus } from './course-status';
import { FilePermission } from './file-permission';
import { CoursePublicationFeedback } from './course-publication-feedback';


export interface CourseDraft { 
    key: string;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date;
    publishedAt?: Date;
    archivedAt?: Date;
    status: CourseStatus;
    title: string;
    description?: string;
    author?: string;
    filePermissions: Array<FilePermission>;
    publicationFeedback: Array<CoursePublicationFeedback>;
}
export namespace CourseDraft {
}


