/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CourseStatus = 'DRAFT' | 'PUBLISHED' | 'INVALID' | 'EDITED' | 'ARCHIVED';

export const CourseStatus = {
    Draft: 'DRAFT' as CourseStatus,
    Published: 'PUBLISHED' as CourseStatus,
    Invalid: 'INVALID' as CourseStatus,
    Edited: 'EDITED' as CourseStatus,
    Archived: 'ARCHIVED' as CourseStatus
};

