/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageableObject } from './pageable-object';
import { TestDraft } from './test-draft';
import { SortObject } from './sort-object';


export interface PageTestDraft { 
    totalPages?: number;
    totalElements?: number;
    size?: number;
    content?: Array<TestDraft>;
    first?: boolean;
    last?: boolean;
    number?: number;
    sort?: SortObject;
    numberOfElements?: number;
    pageable?: PageableObject;
    empty?: boolean;
}

