/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionType } from './question-type';


export interface QuestionDraftRequest { 
    type: QuestionType;
    position?: number;
    required?: boolean;
    title?: string;
    description?: string;
    question: string;
    points: number;
    deductionWrongAnswer?: number;
    allowEmpty?: boolean;
    shownAnswers?: number;
    shuffleAnswers: boolean;
    reviewManually: boolean;
}
export namespace QuestionDraftRequest {
}


