/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Group } from './group';
import { User } from './user';
import { MembershipType } from './membership-type';


export interface RoleAssignment { 
    key: string;
    createdAt: Date;
    updatedAt: Date;
    deletedAt?: Date;
    validUntil?: Date;
    validFrom?: Date;
    role: Role;
    type: MembershipType;
    user?: User;
    group?: Group;
}
export namespace RoleAssignment {
}


