/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MembershipType } from './membership-type';


export interface RoleAssignmentRequestCreate { 
    roleKey: string;
    type: MembershipType;
    validFrom?: Date;
    validUntil?: Date;
    userKey?: string;
    groupKey?: string;
    userKeyProvided?: boolean;
    groupKeyProvided?: boolean;
    groupOrUserSet?: boolean;
    validFromInFuture?: boolean;
    validFromBeforeValidUntil?: boolean;
}
export namespace RoleAssignmentRequestCreate {
}


