/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TestExecutionMode } from './test-execution-mode';


export interface TestDraftRequest { 
    title: string;
    description?: string;
    author?: string;
    executionMode: TestExecutionMode;
    pointsToPass?: number;
    percentageToPass?: number;
    duration?: number;
    shuffleQuestions?: boolean;
    shownQuestions?: number;
}
export namespace TestDraftRequest {
}


