/**
 * Famulex API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WebsocketMessageType = 'SYSTEM_HELLO_WORLD' | 'SYSTEM_HELLO_USER' | 'USER_UPDATE_LATEST_ACTIVITY';

export const WebsocketMessageType = {
    SystemHelloWorld: 'SYSTEM_HELLO_WORLD' as WebsocketMessageType,
    SystemHelloUser: 'SYSTEM_HELLO_USER' as WebsocketMessageType,
    UserUpdateLatestActivity: 'USER_UPDATE_LATEST_ACTIVITY' as WebsocketMessageType
};

