/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxAnswerDraftI18n;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxAnswerDraftI18nRecord extends UpdatableRecordImpl<FxAnswerDraftI18nRecord> implements Record7<Long, String, OffsetDateTime, OffsetDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_answer_draft_i18n.fk_answer_draft</code>.
     */
    public void setFkAnswerDraft(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.fk_answer_draft</code>.
     */
    public Long getFkAnswerDraft() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_answer_draft_i18n.language</code>.
     */
    public void setLanguage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.language</code>.
     */
    public String getLanguage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.fx_answer_draft_i18n.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_answer_draft_i18n.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_answer_draft_i18n.title</code>.
     */
    public void setTitle(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.title</code>.
     */
    public String getTitle() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.fx_answer_draft_i18n.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.fx_answer_draft_i18n.content</code>.
     */
    public void setContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_answer_draft_i18n.content</code>.
     */
    public String getContent() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Long, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, OffsetDateTime, OffsetDateTime, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, String, OffsetDateTime, OffsetDateTime, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.FK_ANSWER_DRAFT;
    }

    @Override
    public Field<String> field2() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.LANGUAGE;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.UPDATED_AT;
    }

    @Override
    public Field<String> field5() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.TITLE;
    }

    @Override
    public Field<String> field6() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.DESCRIPTION;
    }

    @Override
    public Field<String> field7() {
        return FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N.CONTENT;
    }

    @Override
    public Long component1() {
        return getFkAnswerDraft();
    }

    @Override
    public String component2() {
        return getLanguage();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public String component5() {
        return getTitle();
    }

    @Override
    public String component6() {
        return getDescription();
    }

    @Override
    public String component7() {
        return getContent();
    }

    @Override
    public Long value1() {
        return getFkAnswerDraft();
    }

    @Override
    public String value2() {
        return getLanguage();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public String value5() {
        return getTitle();
    }

    @Override
    public String value6() {
        return getDescription();
    }

    @Override
    public String value7() {
        return getContent();
    }

    @Override
    public FxAnswerDraftI18nRecord value1(Long value) {
        setFkAnswerDraft(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord value2(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord value5(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord value6(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord value7(String value) {
        setContent(value);
        return this;
    }

    @Override
    public FxAnswerDraftI18nRecord values(Long value1, String value2, OffsetDateTime value3, OffsetDateTime value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxAnswerDraftI18nRecord
     */
    public FxAnswerDraftI18nRecord() {
        super(FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N);
    }

    /**
     * Create a detached, initialised FxAnswerDraftI18nRecord
     */
    public FxAnswerDraftI18nRecord(Long fkAnswerDraft, String language, OffsetDateTime createdAt, OffsetDateTime updatedAt, String title, String description, String content) {
        super(FxAnswerDraftI18n.FX_ANSWER_DRAFT_I18N);

        setFkAnswerDraft(fkAnswerDraft);
        setLanguage(language);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setTitle(title);
        setDescription(description);
        setContent(content);
        resetChangedOnNotNull();
    }
}
