/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxChatToGroup;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxChatToGroupRecord extends UpdatableRecordImpl<FxChatToGroupRecord> implements Record8<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_chat_to_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.valid_until</code>.
     */
    public void setValidUntil(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.valid_until</code>.
     */
    public OffsetDateTime getValidUntil() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.fk_chat</code>.
     */
    public void setFkChat(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.fk_chat</code>.
     */
    public Long getFkChat() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.fx_chat_to_group.fk_group</code>.
     */
    public void setFkGroup(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_chat_to_group.fk_group</code>.
     */
    public Long getFkGroup() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.DELETED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.VALID_UNTIL;
    }

    @Override
    public Field<Long> field7() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.FK_CHAT;
    }

    @Override
    public Field<Long> field8() {
        return FxChatToGroup.FX_CHAT_TO_GROUP.FK_GROUP;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getValidUntil();
    }

    @Override
    public Long component7() {
        return getFkChat();
    }

    @Override
    public Long component8() {
        return getFkGroup();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getValidUntil();
    }

    @Override
    public Long value7() {
        return getFkChat();
    }

    @Override
    public Long value8() {
        return getFkGroup();
    }

    @Override
    public FxChatToGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value5(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value6(OffsetDateTime value) {
        setValidUntil(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value7(Long value) {
        setFkChat(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord value8(Long value) {
        setFkGroup(value);
        return this;
    }

    @Override
    public FxChatToGroupRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxChatToGroupRecord
     */
    public FxChatToGroupRecord() {
        super(FxChatToGroup.FX_CHAT_TO_GROUP);
    }

    /**
     * Create a detached, initialised FxChatToGroupRecord
     */
    public FxChatToGroupRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, OffsetDateTime validUntil, Long fkChat, Long fkGroup) {
        super(FxChatToGroup.FX_CHAT_TO_GROUP);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setValidUntil(validUntil);
        setFkChat(fkChat);
        setFkGroup(fkGroup);
        resetChangedOnNotNull();
    }
}
