/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxCourseToLibrary;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxCourseToLibraryRecord extends UpdatableRecordImpl<FxCourseToLibraryRecord> implements Record9<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_course_to_library.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_course_to_library.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_course_to_library.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_course_to_library.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_course_to_library.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_course_to_library.valid_from</code>.
     */
    public void setValidFrom(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.valid_from</code>.
     */
    public OffsetDateTime getValidFrom() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.fx_course_to_library.valid_until</code>.
     */
    public void setValidUntil(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.valid_until</code>.
     */
    public OffsetDateTime getValidUntil() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.fx_course_to_library.fk_course_library</code>.
     */
    public void setFkCourseLibrary(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.fk_course_library</code>.
     */
    public Long getFkCourseLibrary() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.fx_course_to_library.fk_course</code>.
     */
    public void setFkCourse(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_course_to_library.fk_course</code>.
     */
    public Long getFkCourse() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.DELETED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.VALID_FROM;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.VALID_UNTIL;
    }

    @Override
    public Field<Long> field8() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.FK_COURSE_LIBRARY;
    }

    @Override
    public Field<Long> field9() {
        return FxCourseToLibrary.FX_COURSE_TO_LIBRARY.FK_COURSE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getValidFrom();
    }

    @Override
    public OffsetDateTime component7() {
        return getValidUntil();
    }

    @Override
    public Long component8() {
        return getFkCourseLibrary();
    }

    @Override
    public Long component9() {
        return getFkCourse();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getValidFrom();
    }

    @Override
    public OffsetDateTime value7() {
        return getValidUntil();
    }

    @Override
    public Long value8() {
        return getFkCourseLibrary();
    }

    @Override
    public Long value9() {
        return getFkCourse();
    }

    @Override
    public FxCourseToLibraryRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value5(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value6(OffsetDateTime value) {
        setValidFrom(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value7(OffsetDateTime value) {
        setValidUntil(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value8(Long value) {
        setFkCourseLibrary(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord value9(Long value) {
        setFkCourse(value);
        return this;
    }

    @Override
    public FxCourseToLibraryRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6, OffsetDateTime value7, Long value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxCourseToLibraryRecord
     */
    public FxCourseToLibraryRecord() {
        super(FxCourseToLibrary.FX_COURSE_TO_LIBRARY);
    }

    /**
     * Create a detached, initialised FxCourseToLibraryRecord
     */
    public FxCourseToLibraryRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, OffsetDateTime validFrom, OffsetDateTime validUntil, Long fkCourseLibrary, Long fkCourse) {
        super(FxCourseToLibrary.FX_COURSE_TO_LIBRARY);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setValidFrom(validFrom);
        setValidUntil(validUntil);
        setFkCourseLibrary(fkCourseLibrary);
        setFkCourse(fkCourse);
        resetChangedOnNotNull();
    }
}
