/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxCourseDraft;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxCourseDraftRecord extends UpdatableRecordImpl<FxCourseDraftRecord> implements Record11<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_course_draft.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_course_draft.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_course_draft.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_course_draft.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_course_draft.published_at</code>.
     */
    public void setPublishedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_course_draft.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.fx_course_draft.archived_at</code>.
     */
    public void setArchivedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.archived_at</code>.
     */
    public OffsetDateTime getArchivedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.fx_course_draft.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.fx_course_draft.title</code>.
     */
    public void setTitle(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.title</code>.
     */
    public String getTitle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.fx_course_draft.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.fx_course_draft.author</code>.
     */
    public void setAuthor(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_course_draft.author</code>.
     */
    public String getAuthor() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, String> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, String> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxCourseDraft.FX_COURSE_DRAFT.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxCourseDraft.FX_COURSE_DRAFT.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxCourseDraft.FX_COURSE_DRAFT.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxCourseDraft.FX_COURSE_DRAFT.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxCourseDraft.FX_COURSE_DRAFT.PUBLISHED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return FxCourseDraft.FX_COURSE_DRAFT.DELETED_AT;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return FxCourseDraft.FX_COURSE_DRAFT.ARCHIVED_AT;
    }

    @Override
    public Field<String> field8() {
        return FxCourseDraft.FX_COURSE_DRAFT.STATUS;
    }

    @Override
    public Field<String> field9() {
        return FxCourseDraft.FX_COURSE_DRAFT.TITLE;
    }

    @Override
    public Field<String> field10() {
        return FxCourseDraft.FX_COURSE_DRAFT.DESCRIPTION;
    }

    @Override
    public Field<String> field11() {
        return FxCourseDraft.FX_COURSE_DRAFT.AUTHOR;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getPublishedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime component7() {
        return getArchivedAt();
    }

    @Override
    public String component8() {
        return getStatus();
    }

    @Override
    public String component9() {
        return getTitle();
    }

    @Override
    public String component10() {
        return getDescription();
    }

    @Override
    public String component11() {
        return getAuthor();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getPublishedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime value7() {
        return getArchivedAt();
    }

    @Override
    public String value8() {
        return getStatus();
    }

    @Override
    public String value9() {
        return getTitle();
    }

    @Override
    public String value10() {
        return getDescription();
    }

    @Override
    public String value11() {
        return getAuthor();
    }

    @Override
    public FxCourseDraftRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value5(OffsetDateTime value) {
        setPublishedAt(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value6(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value7(OffsetDateTime value) {
        setArchivedAt(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value8(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value9(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value10(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord value11(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public FxCourseDraftRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6, OffsetDateTime value7, String value8, String value9, String value10, String value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxCourseDraftRecord
     */
    public FxCourseDraftRecord() {
        super(FxCourseDraft.FX_COURSE_DRAFT);
    }

    /**
     * Create a detached, initialised FxCourseDraftRecord
     */
    public FxCourseDraftRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime publishedAt, OffsetDateTime deletedAt, OffsetDateTime archivedAt, String status, String title, String description, String author) {
        super(FxCourseDraft.FX_COURSE_DRAFT);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setPublishedAt(publishedAt);
        setDeletedAt(deletedAt);
        setArchivedAt(archivedAt);
        setStatus(status);
        setTitle(title);
        setDescription(description);
        setAuthor(author);
        resetChangedOnNotNull();
    }
}
