/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxFile;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxFileRecord extends UpdatableRecordImpl<FxFileRecord> implements Record11<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, Long, Integer, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_file.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_file.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_file.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_file.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_file.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_file.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_file.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_file.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_file.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_file.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_file.file_name</code>.
     */
    public void setFileName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_file.file_name</code>.
     */
    public String getFileName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.fx_file.mime_type</code>.
     */
    public void setMimeType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_file.mime_type</code>.
     */
    public String getMimeType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.fx_file.file_extension</code>.
     */
    public void setFileExtension(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_file.file_extension</code>.
     */
    public String getFileExtension() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.fx_file.file_size</code>.
     */
    public void setFileSize(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_file.file_size</code>.
     */
    public Long getFileSize() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.fx_file.length</code>.
     */
    public void setLength(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_file.length</code>.
     */
    public Integer getLength() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.fx_file.fk_creator</code>.
     */
    public void setFkCreator(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_file.fk_creator</code>.
     */
    public Long getFkCreator() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, Long, Integer, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, String, String, Long, Integer, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxFile.FX_FILE.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxFile.FX_FILE.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxFile.FX_FILE.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxFile.FX_FILE.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxFile.FX_FILE.DELETED_AT;
    }

    @Override
    public Field<String> field6() {
        return FxFile.FX_FILE.FILE_NAME;
    }

    @Override
    public Field<String> field7() {
        return FxFile.FX_FILE.MIME_TYPE;
    }

    @Override
    public Field<String> field8() {
        return FxFile.FX_FILE.FILE_EXTENSION;
    }

    @Override
    public Field<Long> field9() {
        return FxFile.FX_FILE.FILE_SIZE;
    }

    @Override
    public Field<Integer> field10() {
        return FxFile.FX_FILE.LENGTH;
    }

    @Override
    public Field<Long> field11() {
        return FxFile.FX_FILE.FK_CREATOR;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public String component6() {
        return getFileName();
    }

    @Override
    public String component7() {
        return getMimeType();
    }

    @Override
    public String component8() {
        return getFileExtension();
    }

    @Override
    public Long component9() {
        return getFileSize();
    }

    @Override
    public Integer component10() {
        return getLength();
    }

    @Override
    public Long component11() {
        return getFkCreator();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public String value6() {
        return getFileName();
    }

    @Override
    public String value7() {
        return getMimeType();
    }

    @Override
    public String value8() {
        return getFileExtension();
    }

    @Override
    public Long value9() {
        return getFileSize();
    }

    @Override
    public Integer value10() {
        return getLength();
    }

    @Override
    public Long value11() {
        return getFkCreator();
    }

    @Override
    public FxFileRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxFileRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxFileRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxFileRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxFileRecord value5(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxFileRecord value6(String value) {
        setFileName(value);
        return this;
    }

    @Override
    public FxFileRecord value7(String value) {
        setMimeType(value);
        return this;
    }

    @Override
    public FxFileRecord value8(String value) {
        setFileExtension(value);
        return this;
    }

    @Override
    public FxFileRecord value9(Long value) {
        setFileSize(value);
        return this;
    }

    @Override
    public FxFileRecord value10(Integer value) {
        setLength(value);
        return this;
    }

    @Override
    public FxFileRecord value11(Long value) {
        setFkCreator(value);
        return this;
    }

    @Override
    public FxFileRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, String value6, String value7, String value8, Long value9, Integer value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxFileRecord
     */
    public FxFileRecord() {
        super(FxFile.FX_FILE);
    }

    /**
     * Create a detached, initialised FxFileRecord
     */
    public FxFileRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, String fileName, String mimeType, String fileExtension, Long fileSize, Integer length, Long fkCreator) {
        super(FxFile.FX_FILE);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setFileName(fileName);
        setMimeType(mimeType);
        setFileExtension(fileExtension);
        setFileSize(fileSize);
        setLength(length);
        setFkCreator(fkCreator);
        resetChangedOnNotNull();
    }
}
