/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxFilePermission;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxFilePermissionRecord extends UpdatableRecordImpl<FxFilePermissionRecord> implements Record16<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Integer, Long, Long, Long, Long, Long, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_file_permission.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_file_permission.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_file_permission.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_file_permission.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_file_permission.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_file_permission.valid_from</code>.
     */
    public void setValidFrom(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.valid_from</code>.
     */
    public OffsetDateTime getValidFrom() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.fx_file_permission.valid_until</code>.
     */
    public void setValidUntil(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.valid_until</code>.
     */
    public OffsetDateTime getValidUntil() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.fx_file_permission.type</code>.
     */
    public void setType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.type</code>.
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.fx_file_permission.position</code>.
     */
    public void setPosition(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_file</code>.
     */
    public void setFkFile(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_file</code>.
     */
    public Long getFkFile() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_user</code>.
     */
    public void setFkUser(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_user</code>.
     */
    public Long getFkUser() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_group</code>.
     */
    public void setFkGroup(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_group</code>.
     */
    public Long getFkGroup() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_course</code>.
     */
    public void setFkCourse(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_course</code>.
     */
    public Long getFkCourse() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_course_item</code>.
     */
    public void setFkCourseItem(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_course_item</code>.
     */
    public Long getFkCourseItem() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_course_draft</code>.
     */
    public void setFkCourseDraft(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_course_draft</code>.
     */
    public Long getFkCourseDraft() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>public.fx_file_permission.fk_course_draft_item</code>.
     */
    public void setFkCourseDraftItem(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.fx_file_permission.fk_course_draft_item</code>.
     */
    public Long getFkCourseDraftItem() {
        return (Long) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Integer, Long, Long, Long, Long, Long, Long, Long> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Integer, Long, Long, Long, Long, Long, Long, Long> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxFilePermission.FX_FILE_PERMISSION.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxFilePermission.FX_FILE_PERMISSION.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxFilePermission.FX_FILE_PERMISSION.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxFilePermission.FX_FILE_PERMISSION.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxFilePermission.FX_FILE_PERMISSION.DELETED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return FxFilePermission.FX_FILE_PERMISSION.VALID_FROM;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return FxFilePermission.FX_FILE_PERMISSION.VALID_UNTIL;
    }

    @Override
    public Field<String> field8() {
        return FxFilePermission.FX_FILE_PERMISSION.TYPE;
    }

    @Override
    public Field<Integer> field9() {
        return FxFilePermission.FX_FILE_PERMISSION.POSITION;
    }

    @Override
    public Field<Long> field10() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_FILE;
    }

    @Override
    public Field<Long> field11() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_USER;
    }

    @Override
    public Field<Long> field12() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_GROUP;
    }

    @Override
    public Field<Long> field13() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_COURSE;
    }

    @Override
    public Field<Long> field14() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_COURSE_ITEM;
    }

    @Override
    public Field<Long> field15() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_COURSE_DRAFT;
    }

    @Override
    public Field<Long> field16() {
        return FxFilePermission.FX_FILE_PERMISSION.FK_COURSE_DRAFT_ITEM;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getValidFrom();
    }

    @Override
    public OffsetDateTime component7() {
        return getValidUntil();
    }

    @Override
    public String component8() {
        return getType();
    }

    @Override
    public Integer component9() {
        return getPosition();
    }

    @Override
    public Long component10() {
        return getFkFile();
    }

    @Override
    public Long component11() {
        return getFkUser();
    }

    @Override
    public Long component12() {
        return getFkGroup();
    }

    @Override
    public Long component13() {
        return getFkCourse();
    }

    @Override
    public Long component14() {
        return getFkCourseItem();
    }

    @Override
    public Long component15() {
        return getFkCourseDraft();
    }

    @Override
    public Long component16() {
        return getFkCourseDraftItem();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getValidFrom();
    }

    @Override
    public OffsetDateTime value7() {
        return getValidUntil();
    }

    @Override
    public String value8() {
        return getType();
    }

    @Override
    public Integer value9() {
        return getPosition();
    }

    @Override
    public Long value10() {
        return getFkFile();
    }

    @Override
    public Long value11() {
        return getFkUser();
    }

    @Override
    public Long value12() {
        return getFkGroup();
    }

    @Override
    public Long value13() {
        return getFkCourse();
    }

    @Override
    public Long value14() {
        return getFkCourseItem();
    }

    @Override
    public Long value15() {
        return getFkCourseDraft();
    }

    @Override
    public Long value16() {
        return getFkCourseDraftItem();
    }

    @Override
    public FxFilePermissionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value5(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value6(OffsetDateTime value) {
        setValidFrom(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value7(OffsetDateTime value) {
        setValidUntil(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value8(String value) {
        setType(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value9(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value10(Long value) {
        setFkFile(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value11(Long value) {
        setFkUser(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value12(Long value) {
        setFkGroup(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value13(Long value) {
        setFkCourse(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value14(Long value) {
        setFkCourseItem(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value15(Long value) {
        setFkCourseDraft(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord value16(Long value) {
        setFkCourseDraftItem(value);
        return this;
    }

    @Override
    public FxFilePermissionRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6, OffsetDateTime value7, String value8, Integer value9, Long value10, Long value11, Long value12, Long value13, Long value14, Long value15, Long value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxFilePermissionRecord
     */
    public FxFilePermissionRecord() {
        super(FxFilePermission.FX_FILE_PERMISSION);
    }

    /**
     * Create a detached, initialised FxFilePermissionRecord
     */
    public FxFilePermissionRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, OffsetDateTime validFrom, OffsetDateTime validUntil, String type, Integer position, Long fkFile, Long fkUser, Long fkGroup, Long fkCourse, Long fkCourseItem, Long fkCourseDraft, Long fkCourseDraftItem) {
        super(FxFilePermission.FX_FILE_PERMISSION);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setValidFrom(validFrom);
        setValidUntil(validUntil);
        setType(type);
        setPosition(position);
        setFkFile(fkFile);
        setFkUser(fkUser);
        setFkGroup(fkGroup);
        setFkCourse(fkCourse);
        setFkCourseItem(fkCourseItem);
        setFkCourseDraft(fkCourseDraft);
        setFkCourseDraftItem(fkCourseDraftItem);
        resetChangedOnNotNull();
    }
}
