/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxGroup;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxGroupRecord extends UpdatableRecordImpl<FxGroupRecord> implements Record7<Long, UUID, OffsetDateTime, OffsetDateTime, String, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_group.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_group.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_group.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_group.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_group.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_group.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_group.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_group.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_group.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_group.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.fx_group.name</code>.
     */
    public void setName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_group.name</code>.
     */
    public String getName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.fx_group.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_group.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, UUID, OffsetDateTime, OffsetDateTime, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, UUID, OffsetDateTime, OffsetDateTime, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxGroup.FX_GROUP.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxGroup.FX_GROUP.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxGroup.FX_GROUP.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxGroup.FX_GROUP.UPDATED_AT;
    }

    @Override
    public Field<String> field5() {
        return FxGroup.FX_GROUP.TYPE;
    }

    @Override
    public Field<String> field6() {
        return FxGroup.FX_GROUP.NAME;
    }

    @Override
    public Field<String> field7() {
        return FxGroup.FX_GROUP.DESCRIPTION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public String component5() {
        return getType();
    }

    @Override
    public String component6() {
        return getName();
    }

    @Override
    public String component7() {
        return getDescription();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public String value5() {
        return getType();
    }

    @Override
    public String value6() {
        return getName();
    }

    @Override
    public String value7() {
        return getDescription();
    }

    @Override
    public FxGroupRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxGroupRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxGroupRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxGroupRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxGroupRecord value5(String value) {
        setType(value);
        return this;
    }

    @Override
    public FxGroupRecord value6(String value) {
        setName(value);
        return this;
    }

    @Override
    public FxGroupRecord value7(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FxGroupRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxGroupRecord
     */
    public FxGroupRecord() {
        super(FxGroup.FX_GROUP);
    }

    /**
     * Create a detached, initialised FxGroupRecord
     */
    public FxGroupRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, String type, String name, String description) {
        super(FxGroup.FX_GROUP);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setType(type);
        setName(name);
        setDescription(description);
        resetChangedOnNotNull();
    }
}
