/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxGroupMembership;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxGroupMembershipRecord extends UpdatableRecordImpl<FxGroupMembershipRecord> implements Record10<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_group_membership.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_group_membership.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_group_membership.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_group_membership.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_group_membership.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_group_membership.valid_from</code>.
     */
    public void setValidFrom(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.valid_from</code>.
     */
    public OffsetDateTime getValidFrom() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.fx_group_membership.valid_until</code>.
     */
    public void setValidUntil(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.valid_until</code>.
     */
    public OffsetDateTime getValidUntil() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.fx_group_membership.role</code>.
     */
    public void setRole(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.role</code>.
     */
    public String getRole() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.fx_group_membership.fk_user</code>.
     */
    public void setFkUser(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.fk_user</code>.
     */
    public Long getFkUser() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>public.fx_group_membership.fk_group</code>.
     */
    public void setFkGroup(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_group_membership.fk_group</code>.
     */
    public Long getFkGroup() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Long, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Long, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.DELETED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.VALID_FROM;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.VALID_UNTIL;
    }

    @Override
    public Field<String> field8() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.ROLE;
    }

    @Override
    public Field<Long> field9() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.FK_USER;
    }

    @Override
    public Field<Long> field10() {
        return FxGroupMembership.FX_GROUP_MEMBERSHIP.FK_GROUP;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getValidFrom();
    }

    @Override
    public OffsetDateTime component7() {
        return getValidUntil();
    }

    @Override
    public String component8() {
        return getRole();
    }

    @Override
    public Long component9() {
        return getFkUser();
    }

    @Override
    public Long component10() {
        return getFkGroup();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getValidFrom();
    }

    @Override
    public OffsetDateTime value7() {
        return getValidUntil();
    }

    @Override
    public String value8() {
        return getRole();
    }

    @Override
    public Long value9() {
        return getFkUser();
    }

    @Override
    public Long value10() {
        return getFkGroup();
    }

    @Override
    public FxGroupMembershipRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value5(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value6(OffsetDateTime value) {
        setValidFrom(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value7(OffsetDateTime value) {
        setValidUntil(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value8(String value) {
        setRole(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value9(Long value) {
        setFkUser(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord value10(Long value) {
        setFkGroup(value);
        return this;
    }

    @Override
    public FxGroupMembershipRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6, OffsetDateTime value7, String value8, Long value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxGroupMembershipRecord
     */
    public FxGroupMembershipRecord() {
        super(FxGroupMembership.FX_GROUP_MEMBERSHIP);
    }

    /**
     * Create a detached, initialised FxGroupMembershipRecord
     */
    public FxGroupMembershipRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, OffsetDateTime validFrom, OffsetDateTime validUntil, String role, Long fkUser, Long fkGroup) {
        super(FxGroupMembership.FX_GROUP_MEMBERSHIP);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setValidFrom(validFrom);
        setValidUntil(validUntil);
        setRole(role);
        setFkUser(fkUser);
        setFkGroup(fkGroup);
        resetChangedOnNotNull();
    }
}
