/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxTestDraft;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestDraftRecord extends UpdatableRecordImpl<FxTestDraftRecord> implements Record18<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, String, String, String, String, String, Double, Double, Integer, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_test_draft.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_test_draft.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_test_draft.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_test_draft.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_test_draft.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>public.fx_test_draft.archived_at</code>.
     */
    public void setArchivedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.archived_at</code>.
     */
    public OffsetDateTime getArchivedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.fx_test_draft.published_at</code>.
     */
    public void setPublishedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.published_at</code>.
     */
    public OffsetDateTime getPublishedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.fx_test_draft.published_version</code>.
     */
    public void setPublishedVersion(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.published_version</code>.
     */
    public Long getPublishedVersion() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.fx_test_draft.status</code>.
     */
    public void setStatus(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.status</code>.
     */
    public String getStatus() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.fx_test_draft.title</code>.
     */
    public void setTitle(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.title</code>.
     */
    public String getTitle() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.fx_test_draft.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.fx_test_draft.author</code>.
     */
    public void setAuthor(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.author</code>.
     */
    public String getAuthor() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.fx_test_draft.execution_mode</code>.
     */
    public void setExecutionMode(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.execution_mode</code>.
     */
    public String getExecutionMode() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.fx_test_draft.points_to_pass</code>.
     */
    public void setPointsToPass(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.points_to_pass</code>.
     */
    public Double getPointsToPass() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>public.fx_test_draft.percentage_to_pass</code>.
     */
    public void setPercentageToPass(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.percentage_to_pass</code>.
     */
    public Double getPercentageToPass() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>public.fx_test_draft.duration</code>.
     */
    public void setDuration(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.duration</code>.
     */
    public Integer getDuration() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.fx_test_draft.shuffle_sections</code>.
     */
    public void setShuffleSections(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.shuffle_sections</code>.
     */
    public Boolean getShuffleSections() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.fx_test_draft.shuffle_questions</code>.
     */
    public void setShuffleQuestions(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.fx_test_draft.shuffle_questions</code>.
     */
    public Boolean getShuffleQuestions() {
        return (Boolean) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, String, String, String, String, String, Double, Double, Integer, Boolean, Boolean> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, String, String, String, String, String, Double, Double, Integer, Boolean, Boolean> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxTestDraft.FX_TEST_DRAFT.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxTestDraft.FX_TEST_DRAFT.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxTestDraft.FX_TEST_DRAFT.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxTestDraft.FX_TEST_DRAFT.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field5() {
        return FxTestDraft.FX_TEST_DRAFT.DELETED_AT;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return FxTestDraft.FX_TEST_DRAFT.ARCHIVED_AT;
    }

    @Override
    public Field<OffsetDateTime> field7() {
        return FxTestDraft.FX_TEST_DRAFT.PUBLISHED_AT;
    }

    @Override
    public Field<Long> field8() {
        return FxTestDraft.FX_TEST_DRAFT.PUBLISHED_VERSION;
    }

    @Override
    public Field<String> field9() {
        return FxTestDraft.FX_TEST_DRAFT.STATUS;
    }

    @Override
    public Field<String> field10() {
        return FxTestDraft.FX_TEST_DRAFT.TITLE;
    }

    @Override
    public Field<String> field11() {
        return FxTestDraft.FX_TEST_DRAFT.DESCRIPTION;
    }

    @Override
    public Field<String> field12() {
        return FxTestDraft.FX_TEST_DRAFT.AUTHOR;
    }

    @Override
    public Field<String> field13() {
        return FxTestDraft.FX_TEST_DRAFT.EXECUTION_MODE;
    }

    @Override
    public Field<Double> field14() {
        return FxTestDraft.FX_TEST_DRAFT.POINTS_TO_PASS;
    }

    @Override
    public Field<Double> field15() {
        return FxTestDraft.FX_TEST_DRAFT.PERCENTAGE_TO_PASS;
    }

    @Override
    public Field<Integer> field16() {
        return FxTestDraft.FX_TEST_DRAFT.DURATION;
    }

    @Override
    public Field<Boolean> field17() {
        return FxTestDraft.FX_TEST_DRAFT.SHUFFLE_SECTIONS;
    }

    @Override
    public Field<Boolean> field18() {
        return FxTestDraft.FX_TEST_DRAFT.SHUFFLE_QUESTIONS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime component6() {
        return getArchivedAt();
    }

    @Override
    public OffsetDateTime component7() {
        return getPublishedAt();
    }

    @Override
    public Long component8() {
        return getPublishedVersion();
    }

    @Override
    public String component9() {
        return getStatus();
    }

    @Override
    public String component10() {
        return getTitle();
    }

    @Override
    public String component11() {
        return getDescription();
    }

    @Override
    public String component12() {
        return getAuthor();
    }

    @Override
    public String component13() {
        return getExecutionMode();
    }

    @Override
    public Double component14() {
        return getPointsToPass();
    }

    @Override
    public Double component15() {
        return getPercentageToPass();
    }

    @Override
    public Integer component16() {
        return getDuration();
    }

    @Override
    public Boolean component17() {
        return getShuffleSections();
    }

    @Override
    public Boolean component18() {
        return getShuffleQuestions();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value5() {
        return getDeletedAt();
    }

    @Override
    public OffsetDateTime value6() {
        return getArchivedAt();
    }

    @Override
    public OffsetDateTime value7() {
        return getPublishedAt();
    }

    @Override
    public Long value8() {
        return getPublishedVersion();
    }

    @Override
    public String value9() {
        return getStatus();
    }

    @Override
    public String value10() {
        return getTitle();
    }

    @Override
    public String value11() {
        return getDescription();
    }

    @Override
    public String value12() {
        return getAuthor();
    }

    @Override
    public String value13() {
        return getExecutionMode();
    }

    @Override
    public Double value14() {
        return getPointsToPass();
    }

    @Override
    public Double value15() {
        return getPercentageToPass();
    }

    @Override
    public Integer value16() {
        return getDuration();
    }

    @Override
    public Boolean value17() {
        return getShuffleSections();
    }

    @Override
    public Boolean value18() {
        return getShuffleQuestions();
    }

    @Override
    public FxTestDraftRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value5(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value6(OffsetDateTime value) {
        setArchivedAt(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value7(OffsetDateTime value) {
        setPublishedAt(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value8(Long value) {
        setPublishedVersion(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value9(String value) {
        setStatus(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value10(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value11(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value12(String value) {
        setAuthor(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value13(String value) {
        setExecutionMode(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value14(Double value) {
        setPointsToPass(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value15(Double value) {
        setPercentageToPass(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value16(Integer value) {
        setDuration(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value17(Boolean value) {
        setShuffleSections(value);
        return this;
    }

    @Override
    public FxTestDraftRecord value18(Boolean value) {
        setShuffleQuestions(value);
        return this;
    }

    @Override
    public FxTestDraftRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, OffsetDateTime value5, OffsetDateTime value6, OffsetDateTime value7, Long value8, String value9, String value10, String value11, String value12, String value13, Double value14, Double value15, Integer value16, Boolean value17, Boolean value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxTestDraftRecord
     */
    public FxTestDraftRecord() {
        super(FxTestDraft.FX_TEST_DRAFT);
    }

    /**
     * Create a detached, initialised FxTestDraftRecord
     */
    public FxTestDraftRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt, OffsetDateTime archivedAt, OffsetDateTime publishedAt, Long publishedVersion, String status, String title, String description, String author, String executionMode, Double pointsToPass, Double percentageToPass, Integer duration, Boolean shuffleSections, Boolean shuffleQuestions) {
        super(FxTestDraft.FX_TEST_DRAFT);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        setArchivedAt(archivedAt);
        setPublishedAt(publishedAt);
        setPublishedVersion(publishedVersion);
        setStatus(status);
        setTitle(title);
        setDescription(description);
        setAuthor(author);
        setExecutionMode(executionMode);
        setPointsToPass(pointsToPass);
        setPercentageToPass(percentageToPass);
        setDuration(duration);
        setShuffleSections(shuffleSections);
        setShuffleQuestions(shuffleQuestions);
        resetChangedOnNotNull();
    }
}
