/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxTestExecutionAnswer;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestExecutionAnswerRecord extends UpdatableRecordImpl<FxTestExecutionAnswerRecord> implements Record9<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, Boolean, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_test_execution_answer.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.fk_answer</code>.
     */
    public void setFkAnswer(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.fk_answer</code>.
     */
    public Long getFkAnswer() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>public.fx_test_execution_answer.fk_test_execution_question</code>.
     */
    public void setFkTestExecutionQuestion(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>public.fx_test_execution_answer.fk_test_execution_question</code>.
     */
    public Long getFkTestExecutionQuestion() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.position</code>.
     */
    public void setPosition(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.selected</code>.
     */
    public void setSelected(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.selected</code>.
     */
    public Boolean getSelected() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.fx_test_execution_answer.content</code>.
     */
    public void setContent(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_test_execution_answer.content</code>.
     */
    public String getContent() {
        return (String) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, Boolean, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, Boolean, String> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.UPDATED_AT;
    }

    @Override
    public Field<Long> field5() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.FK_ANSWER;
    }

    @Override
    public Field<Long> field6() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.FK_TEST_EXECUTION_QUESTION;
    }

    @Override
    public Field<Integer> field7() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.POSITION;
    }

    @Override
    public Field<Boolean> field8() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.SELECTED;
    }

    @Override
    public Field<String> field9() {
        return FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER.CONTENT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public Long component5() {
        return getFkAnswer();
    }

    @Override
    public Long component6() {
        return getFkTestExecutionQuestion();
    }

    @Override
    public Integer component7() {
        return getPosition();
    }

    @Override
    public Boolean component8() {
        return getSelected();
    }

    @Override
    public String component9() {
        return getContent();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public Long value5() {
        return getFkAnswer();
    }

    @Override
    public Long value6() {
        return getFkTestExecutionQuestion();
    }

    @Override
    public Integer value7() {
        return getPosition();
    }

    @Override
    public Boolean value8() {
        return getSelected();
    }

    @Override
    public String value9() {
        return getContent();
    }

    @Override
    public FxTestExecutionAnswerRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value5(Long value) {
        setFkAnswer(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value6(Long value) {
        setFkTestExecutionQuestion(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value7(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value8(Boolean value) {
        setSelected(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord value9(String value) {
        setContent(value);
        return this;
    }

    @Override
    public FxTestExecutionAnswerRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, Long value5, Long value6, Integer value7, Boolean value8, String value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxTestExecutionAnswerRecord
     */
    public FxTestExecutionAnswerRecord() {
        super(FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER);
    }

    /**
     * Create a detached, initialised FxTestExecutionAnswerRecord
     */
    public FxTestExecutionAnswerRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, Long fkAnswer, Long fkTestExecutionQuestion, Integer position, Boolean selected, String content) {
        super(FxTestExecutionAnswer.FX_TEST_EXECUTION_ANSWER);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setFkAnswer(fkAnswer);
        setFkTestExecutionQuestion(fkTestExecutionQuestion);
        setPosition(position);
        setSelected(selected);
        setContent(content);
        resetChangedOnNotNull();
    }
}
