/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxTestSection;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestSectionRecord extends UpdatableRecordImpl<FxTestSectionRecord> implements Record13<Long, UUID, OffsetDateTime, Integer, Long, Long, Long, Integer, String, String, String, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_test_section.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_test_section.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_test_section.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_test_section.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_test_section.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_test_section.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_test_section.version</code>.
     */
    public void setVersion(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_test_section.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.fx_test_section.fk_section_draft</code>.
     */
    public void setFkSectionDraft(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_test_section.fk_section_draft</code>.
     */
    public Long getFkSectionDraft() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.fx_test_section.fk_test</code>.
     */
    public void setFkTest(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_test_section.fk_test</code>.
     */
    public Long getFkTest() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.fx_test_section.fk_parent</code>.
     */
    public void setFkParent(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_test_section.fk_parent</code>.
     */
    public Long getFkParent() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.fx_test_section.position</code>.
     */
    public void setPosition(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_test_section.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.fx_test_section.type</code>.
     */
    public void setType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_test_section.type</code>.
     */
    public String getType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.fx_test_section.title</code>.
     */
    public void setTitle(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_test_section.title</code>.
     */
    public String getTitle() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.fx_test_section.description</code>.
     */
    public void setDescription(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_test_section.description</code>.
     */
    public String getDescription() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.fx_test_section.shown_questions</code>.
     */
    public void setShownQuestions(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.fx_test_section.shown_questions</code>.
     */
    public Integer getShownQuestions() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.fx_test_section.shuffle_questions</code>.
     */
    public void setShuffleQuestions(Boolean value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.fx_test_section.shuffle_questions</code>.
     */
    public Boolean getShuffleQuestions() {
        return (Boolean) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, UUID, OffsetDateTime, Integer, Long, Long, Long, Integer, String, String, String, Integer, Boolean> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, UUID, OffsetDateTime, Integer, Long, Long, Long, Integer, String, String, String, Integer, Boolean> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxTestSection.FX_TEST_SECTION.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxTestSection.FX_TEST_SECTION.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxTestSection.FX_TEST_SECTION.CREATED_AT;
    }

    @Override
    public Field<Integer> field4() {
        return FxTestSection.FX_TEST_SECTION.VERSION;
    }

    @Override
    public Field<Long> field5() {
        return FxTestSection.FX_TEST_SECTION.FK_SECTION_DRAFT;
    }

    @Override
    public Field<Long> field6() {
        return FxTestSection.FX_TEST_SECTION.FK_TEST;
    }

    @Override
    public Field<Long> field7() {
        return FxTestSection.FX_TEST_SECTION.FK_PARENT;
    }

    @Override
    public Field<Integer> field8() {
        return FxTestSection.FX_TEST_SECTION.POSITION;
    }

    @Override
    public Field<String> field9() {
        return FxTestSection.FX_TEST_SECTION.TYPE;
    }

    @Override
    public Field<String> field10() {
        return FxTestSection.FX_TEST_SECTION.TITLE;
    }

    @Override
    public Field<String> field11() {
        return FxTestSection.FX_TEST_SECTION.DESCRIPTION;
    }

    @Override
    public Field<Integer> field12() {
        return FxTestSection.FX_TEST_SECTION.SHOWN_QUESTIONS;
    }

    @Override
    public Field<Boolean> field13() {
        return FxTestSection.FX_TEST_SECTION.SHUFFLE_QUESTIONS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public Integer component4() {
        return getVersion();
    }

    @Override
    public Long component5() {
        return getFkSectionDraft();
    }

    @Override
    public Long component6() {
        return getFkTest();
    }

    @Override
    public Long component7() {
        return getFkParent();
    }

    @Override
    public Integer component8() {
        return getPosition();
    }

    @Override
    public String component9() {
        return getType();
    }

    @Override
    public String component10() {
        return getTitle();
    }

    @Override
    public String component11() {
        return getDescription();
    }

    @Override
    public Integer component12() {
        return getShownQuestions();
    }

    @Override
    public Boolean component13() {
        return getShuffleQuestions();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public Integer value4() {
        return getVersion();
    }

    @Override
    public Long value5() {
        return getFkSectionDraft();
    }

    @Override
    public Long value6() {
        return getFkTest();
    }

    @Override
    public Long value7() {
        return getFkParent();
    }

    @Override
    public Integer value8() {
        return getPosition();
    }

    @Override
    public String value9() {
        return getType();
    }

    @Override
    public String value10() {
        return getTitle();
    }

    @Override
    public String value11() {
        return getDescription();
    }

    @Override
    public Integer value12() {
        return getShownQuestions();
    }

    @Override
    public Boolean value13() {
        return getShuffleQuestions();
    }

    @Override
    public FxTestSectionRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value4(Integer value) {
        setVersion(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value5(Long value) {
        setFkSectionDraft(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value6(Long value) {
        setFkTest(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value7(Long value) {
        setFkParent(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value8(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value9(String value) {
        setType(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value10(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value11(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value12(Integer value) {
        setShownQuestions(value);
        return this;
    }

    @Override
    public FxTestSectionRecord value13(Boolean value) {
        setShuffleQuestions(value);
        return this;
    }

    @Override
    public FxTestSectionRecord values(Long value1, UUID value2, OffsetDateTime value3, Integer value4, Long value5, Long value6, Long value7, Integer value8, String value9, String value10, String value11, Integer value12, Boolean value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxTestSectionRecord
     */
    public FxTestSectionRecord() {
        super(FxTestSection.FX_TEST_SECTION);
    }

    /**
     * Create a detached, initialised FxTestSectionRecord
     */
    public FxTestSectionRecord(Long id, UUID key, OffsetDateTime createdAt, Integer version, Long fkSectionDraft, Long fkTest, Long fkParent, Integer position, String type, String title, String description, Integer shownQuestions, Boolean shuffleQuestions) {
        super(FxTestSection.FX_TEST_SECTION);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setVersion(version);
        setFkSectionDraft(fkSectionDraft);
        setFkTest(fkTest);
        setFkParent(fkParent);
        setPosition(position);
        setType(type);
        setTitle(title);
        setDescription(description);
        setShownQuestions(shownQuestions);
        setShuffleQuestions(shuffleQuestions);
        resetChangedOnNotNull();
    }
}
