/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxTestSectionDraft;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestSectionDraftRecord extends UpdatableRecordImpl<FxTestSectionDraftRecord> implements Record12<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, String, String, String, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_test_section_draft.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.fk_test_draft</code>.
     */
    public void setFkTestDraft(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.fk_test_draft</code>.
     */
    public Long getFkTestDraft() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.fk_parent</code>.
     */
    public void setFkParent(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.fk_parent</code>.
     */
    public Long getFkParent() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.position</code>.
     */
    public void setPosition(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.position</code>.
     */
    public Integer getPosition() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.type</code>.
     */
    public void setType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.type</code>.
     */
    public String getType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.title</code>.
     */
    public void setTitle(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.title</code>.
     */
    public String getTitle() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.shown_questions</code>.
     */
    public void setShownQuestions(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.shown_questions</code>.
     */
    public Integer getShownQuestions() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.fx_test_section_draft.shuffle_questions</code>.
     */
    public void setShuffleQuestions(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.fx_test_section_draft.shuffle_questions</code>.
     */
    public Boolean getShuffleQuestions() {
        return (Boolean) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, String, String, String, Integer, Boolean> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, String, String, String, Integer, Boolean> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.KEY;
    }

    @Override
    public Field<OffsetDateTime> field3() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field4() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.UPDATED_AT;
    }

    @Override
    public Field<Long> field5() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.FK_TEST_DRAFT;
    }

    @Override
    public Field<Long> field6() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.FK_PARENT;
    }

    @Override
    public Field<Integer> field7() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.POSITION;
    }

    @Override
    public Field<String> field8() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.TYPE;
    }

    @Override
    public Field<String> field9() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.TITLE;
    }

    @Override
    public Field<String> field10() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.DESCRIPTION;
    }

    @Override
    public Field<Integer> field11() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.SHOWN_QUESTIONS;
    }

    @Override
    public Field<Boolean> field12() {
        return FxTestSectionDraft.FX_TEST_SECTION_DRAFT.SHUFFLE_QUESTIONS;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public OffsetDateTime component3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component4() {
        return getUpdatedAt();
    }

    @Override
    public Long component5() {
        return getFkTestDraft();
    }

    @Override
    public Long component6() {
        return getFkParent();
    }

    @Override
    public Integer component7() {
        return getPosition();
    }

    @Override
    public String component8() {
        return getType();
    }

    @Override
    public String component9() {
        return getTitle();
    }

    @Override
    public String component10() {
        return getDescription();
    }

    @Override
    public Integer component11() {
        return getShownQuestions();
    }

    @Override
    public Boolean component12() {
        return getShuffleQuestions();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public OffsetDateTime value3() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value4() {
        return getUpdatedAt();
    }

    @Override
    public Long value5() {
        return getFkTestDraft();
    }

    @Override
    public Long value6() {
        return getFkParent();
    }

    @Override
    public Integer value7() {
        return getPosition();
    }

    @Override
    public String value8() {
        return getType();
    }

    @Override
    public String value9() {
        return getTitle();
    }

    @Override
    public String value10() {
        return getDescription();
    }

    @Override
    public Integer value11() {
        return getShownQuestions();
    }

    @Override
    public Boolean value12() {
        return getShuffleQuestions();
    }

    @Override
    public FxTestSectionDraftRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value3(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value4(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value5(Long value) {
        setFkTestDraft(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value6(Long value) {
        setFkParent(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value7(Integer value) {
        setPosition(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value8(String value) {
        setType(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value9(String value) {
        setTitle(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value10(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value11(Integer value) {
        setShownQuestions(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord value12(Boolean value) {
        setShuffleQuestions(value);
        return this;
    }

    @Override
    public FxTestSectionDraftRecord values(Long value1, UUID value2, OffsetDateTime value3, OffsetDateTime value4, Long value5, Long value6, Integer value7, String value8, String value9, String value10, Integer value11, Boolean value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxTestSectionDraftRecord
     */
    public FxTestSectionDraftRecord() {
        super(FxTestSectionDraft.FX_TEST_SECTION_DRAFT);
    }

    /**
     * Create a detached, initialised FxTestSectionDraftRecord
     */
    public FxTestSectionDraftRecord(Long id, UUID key, OffsetDateTime createdAt, OffsetDateTime updatedAt, Long fkTestDraft, Long fkParent, Integer position, String type, String title, String description, Integer shownQuestions, Boolean shuffleQuestions) {
        super(FxTestSectionDraft.FX_TEST_SECTION_DRAFT);

        setId(id);
        setKey(key);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setFkTestDraft(fkTestDraft);
        setFkParent(fkParent);
        setPosition(position);
        setType(type);
        setTitle(title);
        setDescription(description);
        setShownQuestions(shownQuestions);
        setShuffleQuestions(shuffleQuestions);
        resetChangedOnNotNull();
    }
}
