/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables.records;


import com.famulex.api.jooq.tables.FxUser;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxUserRecord extends UpdatableRecordImpl<FxUserRecord> implements Record13<Long, UUID, String, String, String, String, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.fx_user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.fx_user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.fx_user.key</code>.
     */
    public void setKey(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.fx_user.key</code>.
     */
    public UUID getKey() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.fx_user.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.fx_user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.fx_user.username</code>.
     */
    public void setUsername(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.fx_user.username</code>.
     */
    public String getUsername() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.fx_user.password</code>.
     */
    public void setPassword(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.fx_user.password</code>.
     */
    public String getPassword() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.fx_user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.fx_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.fx_user.last_name</code>.
     */
    public void setLastName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.fx_user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.fx_user.language</code>.
     */
    public void setLanguage(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.fx_user.language</code>.
     */
    public String getLanguage() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.fx_user.type</code>.
     */
    public void setType(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.fx_user.type</code>.
     */
    public String getType() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.fx_user.last_active_at</code>.
     */
    public void setLastActiveAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.fx_user.last_active_at</code>.
     */
    public OffsetDateTime getLastActiveAt() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.fx_user.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.fx_user.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(10);
    }

    /**
     * Setter for <code>public.fx_user.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.fx_user.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(11);
    }

    /**
     * Setter for <code>public.fx_user.deleted_at</code>.
     */
    public void setDeletedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.fx_user.deleted_at</code>.
     */
    public OffsetDateTime getDeletedAt() {
        return (OffsetDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, UUID, String, String, String, String, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, UUID, String, String, String, String, String, String, String, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return FxUser.FX_USER.ID;
    }

    @Override
    public Field<UUID> field2() {
        return FxUser.FX_USER.KEY;
    }

    @Override
    public Field<String> field3() {
        return FxUser.FX_USER.EMAIL;
    }

    @Override
    public Field<String> field4() {
        return FxUser.FX_USER.USERNAME;
    }

    @Override
    public Field<String> field5() {
        return FxUser.FX_USER.PASSWORD;
    }

    @Override
    public Field<String> field6() {
        return FxUser.FX_USER.FIRST_NAME;
    }

    @Override
    public Field<String> field7() {
        return FxUser.FX_USER.LAST_NAME;
    }

    @Override
    public Field<String> field8() {
        return FxUser.FX_USER.LANGUAGE;
    }

    @Override
    public Field<String> field9() {
        return FxUser.FX_USER.TYPE;
    }

    @Override
    public Field<OffsetDateTime> field10() {
        return FxUser.FX_USER.LAST_ACTIVE_AT;
    }

    @Override
    public Field<OffsetDateTime> field11() {
        return FxUser.FX_USER.CREATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field12() {
        return FxUser.FX_USER.UPDATED_AT;
    }

    @Override
    public Field<OffsetDateTime> field13() {
        return FxUser.FX_USER.DELETED_AT;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getEmail();
    }

    @Override
    public String component4() {
        return getUsername();
    }

    @Override
    public String component5() {
        return getPassword();
    }

    @Override
    public String component6() {
        return getFirstName();
    }

    @Override
    public String component7() {
        return getLastName();
    }

    @Override
    public String component8() {
        return getLanguage();
    }

    @Override
    public String component9() {
        return getType();
    }

    @Override
    public OffsetDateTime component10() {
        return getLastActiveAt();
    }

    @Override
    public OffsetDateTime component11() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime component12() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime component13() {
        return getDeletedAt();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getEmail();
    }

    @Override
    public String value4() {
        return getUsername();
    }

    @Override
    public String value5() {
        return getPassword();
    }

    @Override
    public String value6() {
        return getFirstName();
    }

    @Override
    public String value7() {
        return getLastName();
    }

    @Override
    public String value8() {
        return getLanguage();
    }

    @Override
    public String value9() {
        return getType();
    }

    @Override
    public OffsetDateTime value10() {
        return getLastActiveAt();
    }

    @Override
    public OffsetDateTime value11() {
        return getCreatedAt();
    }

    @Override
    public OffsetDateTime value12() {
        return getUpdatedAt();
    }

    @Override
    public OffsetDateTime value13() {
        return getDeletedAt();
    }

    @Override
    public FxUserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public FxUserRecord value2(UUID value) {
        setKey(value);
        return this;
    }

    @Override
    public FxUserRecord value3(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public FxUserRecord value4(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public FxUserRecord value5(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public FxUserRecord value6(String value) {
        setFirstName(value);
        return this;
    }

    @Override
    public FxUserRecord value7(String value) {
        setLastName(value);
        return this;
    }

    @Override
    public FxUserRecord value8(String value) {
        setLanguage(value);
        return this;
    }

    @Override
    public FxUserRecord value9(String value) {
        setType(value);
        return this;
    }

    @Override
    public FxUserRecord value10(OffsetDateTime value) {
        setLastActiveAt(value);
        return this;
    }

    @Override
    public FxUserRecord value11(OffsetDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public FxUserRecord value12(OffsetDateTime value) {
        setUpdatedAt(value);
        return this;
    }

    @Override
    public FxUserRecord value13(OffsetDateTime value) {
        setDeletedAt(value);
        return this;
    }

    @Override
    public FxUserRecord values(Long value1, UUID value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, OffsetDateTime value10, OffsetDateTime value11, OffsetDateTime value12, OffsetDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FxUserRecord
     */
    public FxUserRecord() {
        super(FxUser.FX_USER);
    }

    /**
     * Create a detached, initialised FxUserRecord
     */
    public FxUserRecord(Long id, UUID key, String email, String username, String password, String firstName, String lastName, String language, String type, OffsetDateTime lastActiveAt, OffsetDateTime createdAt, OffsetDateTime updatedAt, OffsetDateTime deletedAt) {
        super(FxUser.FX_USER);

        setId(id);
        setKey(key);
        setEmail(email);
        setUsername(username);
        setPassword(password);
        setFirstName(firstName);
        setLastName(lastName);
        setLanguage(language);
        setType(type);
        setLastActiveAt(lastActiveAt);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setDeletedAt(deletedAt);
        resetChangedOnNotNull();
    }
}
