###################################################################################################
# Server Settings
###################################################################################################
server.address=famulex.localhost
###################################################################################################
# Security Settings
###################################################################################################
keycloak.auth-server-url=https://famulex.localhost/auth
###################################################################################################
# Log Level Settings
###################################################################################################
decorator.datasource.p6spy.enable-logging=true
spring.jpa.properties.hibernate.generate_statistics=true
###################################################################################################
# Database Settings
###################################################################################################
spring.datasource.url=jdbc:postgresql://localhost:10000/famulex
spring.datasource.username=famulex
spring.datasource.password=famulex
###################################################################################################
# File Settings
###################################################################################################
files.ssl.enabled=true
###################################################################################################
# OpenApi Settings
###################################################################################################
springdoc.swagger-ui.oauth.clientId=ui
