###################################################################################################
# Server Settings
###################################################################################################
server.address=famulex.localhost
###################################################################################################
# Log Level Settings
###################################################################################################
decorator.datasource.p6spy.enable-logging=true
spring.jpa.properties.hibernate.generate_statistics=true
###################################################################################################
# Database Settings
###################################################################################################
spring.datasource.url=jdbc:postgresql://localhost:10000/famulex
###################################################################################################
# File Settings
###################################################################################################
files.ssl.enabled=true
###################################################################################################
# Security Settings
###################################################################################################
spring.security.oauth2.client.registration.keycloak.client-secret=DAYjWwElJaEosvVbyPLCvF2y6lfRGBxL
api.key=8QAbZhrHfQPAUxxKkUw3PlJEbaZhZuJk7rHBeNDA0kao5t6grx
###################################################################################################
# OpenApi Settings
###################################################################################################
springdoc.swagger-ui.oauth.clientId=ui
