###################################################################################################
# Application Settings
###################################################################################################
server.ssl.enabled=false
server.port=8080
server.host=${SERVER_HOST:famulex.localhost}
server.error.include-stacktrace=never
server.servlet.context-path=${CONTEXT_PATH:/api}
application.title=@name@
application.version=@version@
spring.jpa.open-in-view=false
###################################################################################################
# Log Level Settings
###################################################################################################
logging.level.org.springframework=INFO
logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.boot.autoconfigure.logging=INFO
logging.level.liquibase=INFO
logging.level.com.famulex.api.configuration=DEBUG
logging.level.web=INFO
decorator.datasource.p6spy.enable-logging=false
decorator.datasource.p6spy.multiline=true
decorator.datasource.p6spy.logging=slf4j
decorator.datasource.p6spy.log-format=%(currentTime) | took %(executionTime)ms | %(category) | connection %(connectionId)\n\t%(sql)\n
spring.jpa.properties.hibernate.generate_statistics=false
###################################################################################################
# Database Settings
###################################################################################################
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://db/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/db.changelog-master.xml
spring.jpa.properties.jakarta.persistence.sharedCache.mode=UNSPECIFIED
###################################################################################################
# Time Settings
###################################################################################################
timezone.default=CEST
###################################################################################################
# Security Settings
###################################################################################################
keycloak.auth-server-url=${KEYCLOAK_URL}
keycloak.realm=famulex
authority.jwt.claim=realm_access
authority.jwt.claim.identifier=roles
api.key.header=X-Api-Key
api.key=${API_KEY}
spring.security.oauth2.client.registration.keycloak.client-id=api
spring.security.oauth2.client.registration.keycloak.client-secret=${KEYCLOAK_SECRET}
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
spring.security.oauth2.resourceserver.jwt.issuer-uri=${spring.security.oauth2.client.provider.keycloak.issuer-uri}
###################################################################################################
# CORS Settings
###################################################################################################
cors.origin.domains=${CORS_DOMAINS:https://famulex.localhost,https://famulex.local,http://localhost:4200,http://localhost:4201}
###################################################################################################
# Websocket Settings
###################################################################################################
websocket.path=/ws
###################################################################################################
# File Storage Settings
###################################################################################################
files.directory=${DATA_STORAGE_PATH:${user.dir}/.data}
files.ssl.enabled=false
files.url.timeout=1800
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
###################################################################################################
# OpenApi Settings
###################################################################################################
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/docs
springdoc.swagger-ui.path=/docs/ui
springdoc.show-actuator=false
springdoc.default-produces-media-type=application/json
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.oauth.clientId=ui-web
###################################################################################################
# JobRunr Settings
###################################################################################################
org.jobrunr.dashboard.enabled=true
org.jobrunr.dashboard.port=8090
org.jobrunr.background-job-server.enabled=true
org.jobrunr.background-job-server.poll-interval-in-seconds=60
org.jobrunr.miscellaneous.allow-anonymous-data-usage=false
