###################################################################################################
# Database Settings
###################################################################################################
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:tc:postgresql:15-alpine:///famulex
spring.datasource.username=famulex
spring.datasource.password=famulex
spring.liquibase.enabled=true
###################################################################################################
# Security Settings
###################################################################################################
spring.security.oauth2.client.registration.keycloak.client-secret=DAYjWwElJaEosvVbyPLCvF2y6lfRGBxL
###################################################################################################
# Testing Settings
###################################################################################################
famulex.testing.mail=testing
famulex.testing.mail.host=@famulex.com
