/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxAnswerDraftRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function12;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxAnswerDraft extends TableImpl<FxAnswerDraftRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_answer_draft</code>
     */
    public static final FxAnswerDraft FX_ANSWER_DRAFT = new FxAnswerDraft();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxAnswerDraftRecord> getRecordType() {
        return FxAnswerDraftRecord.class;
    }

    /**
     * The column <code>public.fx_answer_draft.id</code>.
     */
    public final TableField<FxAnswerDraftRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_answer_draft.key</code>.
     */
    public final TableField<FxAnswerDraftRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.created_at</code>.
     */
    public final TableField<FxAnswerDraftRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.updated_at</code>.
     */
    public final TableField<FxAnswerDraftRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.published_at</code>.
     */
    public final TableField<FxAnswerDraftRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.fx_answer_draft.fk_question_draft</code>.
     */
    public final TableField<FxAnswerDraftRecord, Long> FK_QUESTION_DRAFT = createField(DSL.name("fk_question_draft"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.position</code>.
     */
    public final TableField<FxAnswerDraftRecord, Integer> POSITION = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.required</code>.
     */
    public final TableField<FxAnswerDraftRecord, Boolean> REQUIRED = createField(DSL.name("required"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.correct</code>.
     */
    public final TableField<FxAnswerDraftRecord, Boolean> CORRECT = createField(DSL.name("correct"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft.title</code>.
     */
    public final TableField<FxAnswerDraftRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_answer_draft.description</code>.
     */
    public final TableField<FxAnswerDraftRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_answer_draft.content</code>.
     */
    public final TableField<FxAnswerDraftRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    private FxAnswerDraft(Name alias, Table<FxAnswerDraftRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxAnswerDraft(Name alias, Table<FxAnswerDraftRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_answer_draft</code> table reference
     */
    public FxAnswerDraft(String alias) {
        this(DSL.name(alias), FX_ANSWER_DRAFT);
    }

    /**
     * Create an aliased <code>public.fx_answer_draft</code> table reference
     */
    public FxAnswerDraft(Name alias) {
        this(alias, FX_ANSWER_DRAFT);
    }

    /**
     * Create a <code>public.fx_answer_draft</code> table reference
     */
    public FxAnswerDraft() {
        this(DSL.name("fx_answer_draft"), null);
    }

    public <O extends Record> FxAnswerDraft(Table<O> child, ForeignKey<O, FxAnswerDraftRecord> key) {
        super(child, key, FX_ANSWER_DRAFT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxAnswerDraftRecord, Long> getIdentity() {
        return (Identity<FxAnswerDraftRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxAnswerDraftRecord> getPrimaryKey() {
        return Keys.FX_ANSWER_DRAFT_PKEY;
    }

    @Override
    public List<UniqueKey<FxAnswerDraftRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_ANSWER_DRAFT_KEY_KEY);
    }

    @Override
    public List<ForeignKey<FxAnswerDraftRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_ANSWER_DRAFT__FK_QUESTION_DRAFT);
    }

    private transient FxQuestionDraft _fxQuestionDraft;

    /**
     * Get the implicit join path to the <code>public.fx_question_draft</code>
     * table.
     */
    public FxQuestionDraft fxQuestionDraft() {
        if (_fxQuestionDraft == null)
            _fxQuestionDraft = new FxQuestionDraft(this, Keys.FX_ANSWER_DRAFT__FK_QUESTION_DRAFT);

        return _fxQuestionDraft;
    }

    @Override
    public FxAnswerDraft as(String alias) {
        return new FxAnswerDraft(DSL.name(alias), this);
    }

    @Override
    public FxAnswerDraft as(Name alias) {
        return new FxAnswerDraft(alias, this);
    }

    @Override
    public FxAnswerDraft as(Table<?> alias) {
        return new FxAnswerDraft(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAnswerDraft rename(String name) {
        return new FxAnswerDraft(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAnswerDraft rename(Name name) {
        return new FxAnswerDraft(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAnswerDraft rename(Table<?> name) {
        return new FxAnswerDraft(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, Integer, Boolean, Boolean, String, String, String> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function12<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super Integer, ? super Boolean, ? super Boolean, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function12<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super Integer, ? super Boolean, ? super Boolean, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
