/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxAnswerDraftI18nRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxAnswerDraftI18n extends TableImpl<FxAnswerDraftI18nRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_answer_draft_i18n</code>
     */
    public static final FxAnswerDraftI18n FX_ANSWER_DRAFT_I18N = new FxAnswerDraftI18n();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxAnswerDraftI18nRecord> getRecordType() {
        return FxAnswerDraftI18nRecord.class;
    }

    /**
     * The column <code>public.fx_answer_draft_i18n.fk_answer_draft</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, Long> FK_ANSWER_DRAFT = createField(DSL.name("fk_answer_draft"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft_i18n.language</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft_i18n.created_at</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft_i18n.updated_at</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_answer_draft_i18n.title</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_answer_draft_i18n.description</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_answer_draft_i18n.content</code>.
     */
    public final TableField<FxAnswerDraftI18nRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    private FxAnswerDraftI18n(Name alias, Table<FxAnswerDraftI18nRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxAnswerDraftI18n(Name alias, Table<FxAnswerDraftI18nRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_answer_draft_i18n</code> table
     * reference
     */
    public FxAnswerDraftI18n(String alias) {
        this(DSL.name(alias), FX_ANSWER_DRAFT_I18N);
    }

    /**
     * Create an aliased <code>public.fx_answer_draft_i18n</code> table
     * reference
     */
    public FxAnswerDraftI18n(Name alias) {
        this(alias, FX_ANSWER_DRAFT_I18N);
    }

    /**
     * Create a <code>public.fx_answer_draft_i18n</code> table reference
     */
    public FxAnswerDraftI18n() {
        this(DSL.name("fx_answer_draft_i18n"), null);
    }

    public <O extends Record> FxAnswerDraftI18n(Table<O> child, ForeignKey<O, FxAnswerDraftI18nRecord> key) {
        super(child, key, FX_ANSWER_DRAFT_I18N);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FxAnswerDraftI18nRecord> getPrimaryKey() {
        return Keys.PK_ANSWER_DRAFT_I18N;
    }

    @Override
    public List<ForeignKey<FxAnswerDraftI18nRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_ANSWER_DRAFT_I18N__FK_ANSWER_DRAFT);
    }

    private transient FxAnswerDraft _fxAnswerDraft;

    /**
     * Get the implicit join path to the <code>public.fx_answer_draft</code>
     * table.
     */
    public FxAnswerDraft fxAnswerDraft() {
        if (_fxAnswerDraft == null)
            _fxAnswerDraft = new FxAnswerDraft(this, Keys.FX_ANSWER_DRAFT_I18N__FK_ANSWER_DRAFT);

        return _fxAnswerDraft;
    }

    @Override
    public FxAnswerDraftI18n as(String alias) {
        return new FxAnswerDraftI18n(DSL.name(alias), this);
    }

    @Override
    public FxAnswerDraftI18n as(Name alias) {
        return new FxAnswerDraftI18n(alias, this);
    }

    @Override
    public FxAnswerDraftI18n as(Table<?> alias) {
        return new FxAnswerDraftI18n(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAnswerDraftI18n rename(String name) {
        return new FxAnswerDraftI18n(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAnswerDraftI18n rename(Name name) {
        return new FxAnswerDraftI18n(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxAnswerDraftI18n rename(Table<?> name) {
        return new FxAnswerDraftI18n(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, String, OffsetDateTime, OffsetDateTime, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
