/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxChatRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxChat extends TableImpl<FxChatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_chat</code>
     */
    public static final FxChat FX_CHAT = new FxChat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxChatRecord> getRecordType() {
        return FxChatRecord.class;
    }

    /**
     * The column <code>public.fx_chat.id</code>.
     */
    public final TableField<FxChatRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_chat.key</code>.
     */
    public final TableField<FxChatRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_chat.created_at</code>.
     */
    public final TableField<FxChatRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_chat.updated_at</code>.
     */
    public final TableField<FxChatRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_chat.deleted_at</code>.
     */
    public final TableField<FxChatRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    private FxChat(Name alias, Table<FxChatRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxChat(Name alias, Table<FxChatRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_chat</code> table reference
     */
    public FxChat(String alias) {
        this(DSL.name(alias), FX_CHAT);
    }

    /**
     * Create an aliased <code>public.fx_chat</code> table reference
     */
    public FxChat(Name alias) {
        this(alias, FX_CHAT);
    }

    /**
     * Create a <code>public.fx_chat</code> table reference
     */
    public FxChat() {
        this(DSL.name("fx_chat"), null);
    }

    public <O extends Record> FxChat(Table<O> child, ForeignKey<O, FxChatRecord> key) {
        super(child, key, FX_CHAT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxChatRecord, Long> getIdentity() {
        return (Identity<FxChatRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxChatRecord> getPrimaryKey() {
        return Keys.FX_CHAT_PKEY;
    }

    @Override
    public List<UniqueKey<FxChatRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_CHAT_KEY_KEY);
    }

    @Override
    public FxChat as(String alias) {
        return new FxChat(DSL.name(alias), this);
    }

    @Override
    public FxChat as(Name alias) {
        return new FxChat(alias, this);
    }

    @Override
    public FxChat as(Table<?> alias) {
        return new FxChat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxChat rename(String name) {
        return new FxChat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxChat rename(Name name) {
        return new FxChat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxChat rename(Table<?> name) {
        return new FxChat(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
