/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxCourseDraftItemI18nRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function5;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxCourseDraftItemI18n extends TableImpl<FxCourseDraftItemI18nRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_course_draft_item_i18n</code>
     */
    public static final FxCourseDraftItemI18n FX_COURSE_DRAFT_ITEM_I18N = new FxCourseDraftItemI18n();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxCourseDraftItemI18nRecord> getRecordType() {
        return FxCourseDraftItemI18nRecord.class;
    }

    /**
     * The column
     * <code>public.fx_course_draft_item_i18n.fk_course_draft_item</code>.
     */
    public final TableField<FxCourseDraftItemI18nRecord, Long> FK_COURSE_DRAFT_ITEM = createField(DSL.name("fk_course_draft_item"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_draft_item_i18n.language</code>.
     */
    public final TableField<FxCourseDraftItemI18nRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_draft_item_i18n.created_at</code>.
     */
    public final TableField<FxCourseDraftItemI18nRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course_draft_item_i18n.updated_at</code>.
     */
    public final TableField<FxCourseDraftItemI18nRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course_draft_item_i18n.content</code>.
     */
    public final TableField<FxCourseDraftItemI18nRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    private FxCourseDraftItemI18n(Name alias, Table<FxCourseDraftItemI18nRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxCourseDraftItemI18n(Name alias, Table<FxCourseDraftItemI18nRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_course_draft_item_i18n</code> table
     * reference
     */
    public FxCourseDraftItemI18n(String alias) {
        this(DSL.name(alias), FX_COURSE_DRAFT_ITEM_I18N);
    }

    /**
     * Create an aliased <code>public.fx_course_draft_item_i18n</code> table
     * reference
     */
    public FxCourseDraftItemI18n(Name alias) {
        this(alias, FX_COURSE_DRAFT_ITEM_I18N);
    }

    /**
     * Create a <code>public.fx_course_draft_item_i18n</code> table reference
     */
    public FxCourseDraftItemI18n() {
        this(DSL.name("fx_course_draft_item_i18n"), null);
    }

    public <O extends Record> FxCourseDraftItemI18n(Table<O> child, ForeignKey<O, FxCourseDraftItemI18nRecord> key) {
        super(child, key, FX_COURSE_DRAFT_ITEM_I18N);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FxCourseDraftItemI18nRecord> getPrimaryKey() {
        return Keys.PK_COURSE_DRAFT_ITEM_I18N;
    }

    @Override
    public List<ForeignKey<FxCourseDraftItemI18nRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_COURSE_DRAFT_ITEM_I18N__FK_COURSE_ITEM);
    }

    private transient FxCourseDraftItem _fxCourseDraftItem;

    /**
     * Get the implicit join path to the
     * <code>public.fx_course_draft_item</code> table.
     */
    public FxCourseDraftItem fxCourseDraftItem() {
        if (_fxCourseDraftItem == null)
            _fxCourseDraftItem = new FxCourseDraftItem(this, Keys.FX_COURSE_DRAFT_ITEM_I18N__FK_COURSE_ITEM);

        return _fxCourseDraftItem;
    }

    @Override
    public FxCourseDraftItemI18n as(String alias) {
        return new FxCourseDraftItemI18n(DSL.name(alias), this);
    }

    @Override
    public FxCourseDraftItemI18n as(Name alias) {
        return new FxCourseDraftItemI18n(alias, this);
    }

    @Override
    public FxCourseDraftItemI18n as(Table<?> alias) {
        return new FxCourseDraftItemI18n(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseDraftItemI18n rename(String name) {
        return new FxCourseDraftItemI18n(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseDraftItemI18n rename(Name name) {
        return new FxCourseDraftItemI18n(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseDraftItemI18n rename(Table<?> name) {
        return new FxCourseDraftItemI18n(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, String, OffsetDateTime, OffsetDateTime, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function5<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function5<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
