/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxCourseI18nRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxCourseI18n extends TableImpl<FxCourseI18nRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_course_i18n</code>
     */
    public static final FxCourseI18n FX_COURSE_I18N = new FxCourseI18n();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxCourseI18nRecord> getRecordType() {
        return FxCourseI18nRecord.class;
    }

    /**
     * The column <code>public.fx_course_i18n.fk_course</code>.
     */
    public final TableField<FxCourseI18nRecord, Long> FK_COURSE = createField(DSL.name("fk_course"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_i18n.language</code>.
     */
    public final TableField<FxCourseI18nRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_i18n.created_at</code>.
     */
    public final TableField<FxCourseI18nRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course_i18n.updated_at</code>.
     */
    public final TableField<FxCourseI18nRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course_i18n.title</code>.
     */
    public final TableField<FxCourseI18nRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_i18n.description</code>.
     */
    public final TableField<FxCourseI18nRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private FxCourseI18n(Name alias, Table<FxCourseI18nRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxCourseI18n(Name alias, Table<FxCourseI18nRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_course_i18n</code> table reference
     */
    public FxCourseI18n(String alias) {
        this(DSL.name(alias), FX_COURSE_I18N);
    }

    /**
     * Create an aliased <code>public.fx_course_i18n</code> table reference
     */
    public FxCourseI18n(Name alias) {
        this(alias, FX_COURSE_I18N);
    }

    /**
     * Create a <code>public.fx_course_i18n</code> table reference
     */
    public FxCourseI18n() {
        this(DSL.name("fx_course_i18n"), null);
    }

    public <O extends Record> FxCourseI18n(Table<O> child, ForeignKey<O, FxCourseI18nRecord> key) {
        super(child, key, FX_COURSE_I18N);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FxCourseI18nRecord> getPrimaryKey() {
        return Keys.PK_COURSE_I18N;
    }

    @Override
    public List<ForeignKey<FxCourseI18nRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_COURSE_I18N__FK_COURSE);
    }

    private transient FxCourse _fxCourse;

    /**
     * Get the implicit join path to the <code>public.fx_course</code> table.
     */
    public FxCourse fxCourse() {
        if (_fxCourse == null)
            _fxCourse = new FxCourse(this, Keys.FX_COURSE_I18N__FK_COURSE);

        return _fxCourse;
    }

    @Override
    public FxCourseI18n as(String alias) {
        return new FxCourseI18n(DSL.name(alias), this);
    }

    @Override
    public FxCourseI18n as(Name alias) {
        return new FxCourseI18n(alias, this);
    }

    @Override
    public FxCourseI18n as(Table<?> alias) {
        return new FxCourseI18n(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseI18n rename(String name) {
        return new FxCourseI18n(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseI18n rename(Name name) {
        return new FxCourseI18n(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseI18n rename(Table<?> name) {
        return new FxCourseI18n(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
