/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxCourseRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxCourse extends TableImpl<FxCourseRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_course</code>
     */
    public static final FxCourse FX_COURSE = new FxCourse();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxCourseRecord> getRecordType() {
        return FxCourseRecord.class;
    }

    /**
     * The column <code>public.fx_course.id</code>.
     */
    public final TableField<FxCourseRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_course.key</code>.
     */
    public final TableField<FxCourseRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_course.created_at</code>.
     */
    public final TableField<FxCourseRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course.updated_at</code>.
     */
    public final TableField<FxCourseRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course.fk_course_draft</code>.
     */
    public final TableField<FxCourseRecord, Long> FK_COURSE_DRAFT = createField(DSL.name("fk_course_draft"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.fx_course.title</code>.
     */
    public final TableField<FxCourseRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_course.description</code>.
     */
    public final TableField<FxCourseRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_course.author</code>.
     */
    public final TableField<FxCourseRecord, String> AUTHOR = createField(DSL.name("author"), SQLDataType.CLOB, this, "");

    private FxCourse(Name alias, Table<FxCourseRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxCourse(Name alias, Table<FxCourseRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_course</code> table reference
     */
    public FxCourse(String alias) {
        this(DSL.name(alias), FX_COURSE);
    }

    /**
     * Create an aliased <code>public.fx_course</code> table reference
     */
    public FxCourse(Name alias) {
        this(alias, FX_COURSE);
    }

    /**
     * Create a <code>public.fx_course</code> table reference
     */
    public FxCourse() {
        this(DSL.name("fx_course"), null);
    }

    public <O extends Record> FxCourse(Table<O> child, ForeignKey<O, FxCourseRecord> key) {
        super(child, key, FX_COURSE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxCourseRecord, Long> getIdentity() {
        return (Identity<FxCourseRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxCourseRecord> getPrimaryKey() {
        return Keys.FX_COURSE_PKEY;
    }

    @Override
    public List<UniqueKey<FxCourseRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_COURSE_KEY_KEY);
    }

    @Override
    public List<ForeignKey<FxCourseRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_COURSE__FK_COURSE_DRAFT);
    }

    private transient FxCourseDraft _fxCourseDraft;

    /**
     * Get the implicit join path to the <code>public.fx_course_draft</code>
     * table.
     */
    public FxCourseDraft fxCourseDraft() {
        if (_fxCourseDraft == null)
            _fxCourseDraft = new FxCourseDraft(this, Keys.FX_COURSE__FK_COURSE_DRAFT);

        return _fxCourseDraft;
    }

    @Override
    public FxCourse as(String alias) {
        return new FxCourse(DSL.name(alias), this);
    }

    @Override
    public FxCourse as(Name alias) {
        return new FxCourse(alias, this);
    }

    @Override
    public FxCourse as(Table<?> alias) {
        return new FxCourse(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourse rename(String name) {
        return new FxCourse(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourse rename(Name name) {
        return new FxCourse(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourse rename(Table<?> name) {
        return new FxCourse(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, UUID, OffsetDateTime, OffsetDateTime, Long, String, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super String, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
