/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxCourseLibraryRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxCourseLibrary extends TableImpl<FxCourseLibraryRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_course_library</code>
     */
    public static final FxCourseLibrary FX_COURSE_LIBRARY = new FxCourseLibrary();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxCourseLibraryRecord> getRecordType() {
        return FxCourseLibraryRecord.class;
    }

    /**
     * The column <code>public.fx_course_library.id</code>.
     */
    public final TableField<FxCourseLibraryRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_course_library.key</code>.
     */
    public final TableField<FxCourseLibraryRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_library.created_at</code>.
     */
    public final TableField<FxCourseLibraryRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course_library.updated_at</code>.
     */
    public final TableField<FxCourseLibraryRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_course_library.title</code>.
     */
    public final TableField<FxCourseLibraryRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_course_library.description</code>.
     */
    public final TableField<FxCourseLibraryRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB.nullable(false), this, "");

    private FxCourseLibrary(Name alias, Table<FxCourseLibraryRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxCourseLibrary(Name alias, Table<FxCourseLibraryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_course_library</code> table reference
     */
    public FxCourseLibrary(String alias) {
        this(DSL.name(alias), FX_COURSE_LIBRARY);
    }

    /**
     * Create an aliased <code>public.fx_course_library</code> table reference
     */
    public FxCourseLibrary(Name alias) {
        this(alias, FX_COURSE_LIBRARY);
    }

    /**
     * Create a <code>public.fx_course_library</code> table reference
     */
    public FxCourseLibrary() {
        this(DSL.name("fx_course_library"), null);
    }

    public <O extends Record> FxCourseLibrary(Table<O> child, ForeignKey<O, FxCourseLibraryRecord> key) {
        super(child, key, FX_COURSE_LIBRARY);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxCourseLibraryRecord, Long> getIdentity() {
        return (Identity<FxCourseLibraryRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxCourseLibraryRecord> getPrimaryKey() {
        return Keys.FX_COURSE_LIBRARY_PKEY;
    }

    @Override
    public List<UniqueKey<FxCourseLibraryRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_COURSE_LIBRARY_KEY_KEY);
    }

    @Override
    public FxCourseLibrary as(String alias) {
        return new FxCourseLibrary(DSL.name(alias), this);
    }

    @Override
    public FxCourseLibrary as(Name alias) {
        return new FxCourseLibrary(alias, this);
    }

    @Override
    public FxCourseLibrary as(Table<?> alias) {
        return new FxCourseLibrary(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseLibrary rename(String name) {
        return new FxCourseLibrary(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseLibrary rename(Name name) {
        return new FxCourseLibrary(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxCourseLibrary rename(Table<?> name) {
        return new FxCourseLibrary(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, UUID, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
