/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxFileAccessRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxFileAccess extends TableImpl<FxFileAccessRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_file_access</code>
     */
    public static final FxFileAccess FX_FILE_ACCESS = new FxFileAccess();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxFileAccessRecord> getRecordType() {
        return FxFileAccessRecord.class;
    }

    /**
     * The column <code>public.fx_file_access.id</code>.
     */
    public final TableField<FxFileAccessRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_file_access.key</code>.
     */
    public final TableField<FxFileAccessRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_file_access.created_at</code>.
     */
    public final TableField<FxFileAccessRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_file_access.updated_at</code>.
     */
    public final TableField<FxFileAccessRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_file_access.valid_until</code>.
     */
    public final TableField<FxFileAccessRecord, OffsetDateTime> VALID_UNTIL = createField(DSL.name("valid_until"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.fx_file_access.usage_count</code>.
     */
    public final TableField<FxFileAccessRecord, Integer> USAGE_COUNT = createField(DSL.name("usage_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.fx_file_access.fk_file_permission</code>.
     */
    public final TableField<FxFileAccessRecord, Long> FK_FILE_PERMISSION = createField(DSL.name("fk_file_permission"), SQLDataType.BIGINT, this, "");

    private FxFileAccess(Name alias, Table<FxFileAccessRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxFileAccess(Name alias, Table<FxFileAccessRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_file_access</code> table reference
     */
    public FxFileAccess(String alias) {
        this(DSL.name(alias), FX_FILE_ACCESS);
    }

    /**
     * Create an aliased <code>public.fx_file_access</code> table reference
     */
    public FxFileAccess(Name alias) {
        this(alias, FX_FILE_ACCESS);
    }

    /**
     * Create a <code>public.fx_file_access</code> table reference
     */
    public FxFileAccess() {
        this(DSL.name("fx_file_access"), null);
    }

    public <O extends Record> FxFileAccess(Table<O> child, ForeignKey<O, FxFileAccessRecord> key) {
        super(child, key, FX_FILE_ACCESS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxFileAccessRecord, Long> getIdentity() {
        return (Identity<FxFileAccessRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxFileAccessRecord> getPrimaryKey() {
        return Keys.FX_FILE_ACCESS_PKEY;
    }

    @Override
    public List<UniqueKey<FxFileAccessRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_FILE_ACCESS_KEY_KEY);
    }

    @Override
    public List<ForeignKey<FxFileAccessRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_FILE_ACCESS__FK_FILE_PERMISSION);
    }

    private transient FxFilePermission _fxFilePermission;

    /**
     * Get the implicit join path to the <code>public.fx_file_permission</code>
     * table.
     */
    public FxFilePermission fxFilePermission() {
        if (_fxFilePermission == null)
            _fxFilePermission = new FxFilePermission(this, Keys.FX_FILE_ACCESS__FK_FILE_PERMISSION);

        return _fxFilePermission;
    }

    @Override
    public FxFileAccess as(String alias) {
        return new FxFileAccess(DSL.name(alias), this);
    }

    @Override
    public FxFileAccess as(Name alias) {
        return new FxFileAccess(alias, this);
    }

    @Override
    public FxFileAccess as(Table<?> alias) {
        return new FxFileAccess(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxFileAccess rename(String name) {
        return new FxFileAccess(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxFileAccess rename(Name name) {
        return new FxFileAccess(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxFileAccess rename(Table<?> name) {
        return new FxFileAccess(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, Integer, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super Integer, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super Integer, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
