/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxMessageRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function8;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxMessage extends TableImpl<FxMessageRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_message</code>
     */
    public static final FxMessage FX_MESSAGE = new FxMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxMessageRecord> getRecordType() {
        return FxMessageRecord.class;
    }

    /**
     * The column <code>public.fx_message.id</code>.
     */
    public final TableField<FxMessageRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_message.created_at</code>.
     */
    public final TableField<FxMessageRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_message.updated_at</code>.
     */
    public final TableField<FxMessageRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_message.deleted_at</code>.
     */
    public final TableField<FxMessageRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.fx_message.content</code>.
     */
    public final TableField<FxMessageRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_message.fk_parent</code>.
     */
    public final TableField<FxMessageRecord, Long> FK_PARENT = createField(DSL.name("fk_parent"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.fx_message.fk_sender</code>.
     */
    public final TableField<FxMessageRecord, Long> FK_SENDER = createField(DSL.name("fk_sender"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_message.fk_chat</code>.
     */
    public final TableField<FxMessageRecord, Long> FK_CHAT = createField(DSL.name("fk_chat"), SQLDataType.BIGINT.nullable(false), this, "");

    private FxMessage(Name alias, Table<FxMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxMessage(Name alias, Table<FxMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_message</code> table reference
     */
    public FxMessage(String alias) {
        this(DSL.name(alias), FX_MESSAGE);
    }

    /**
     * Create an aliased <code>public.fx_message</code> table reference
     */
    public FxMessage(Name alias) {
        this(alias, FX_MESSAGE);
    }

    /**
     * Create a <code>public.fx_message</code> table reference
     */
    public FxMessage() {
        this(DSL.name("fx_message"), null);
    }

    public <O extends Record> FxMessage(Table<O> child, ForeignKey<O, FxMessageRecord> key) {
        super(child, key, FX_MESSAGE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxMessageRecord, Long> getIdentity() {
        return (Identity<FxMessageRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxMessageRecord> getPrimaryKey() {
        return Keys.FX_MESSAGE_PKEY;
    }

    @Override
    public List<ForeignKey<FxMessageRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_MESSAGE__FK_PARENT, Keys.FX_MESSAGE__FK_SENDER, Keys.FX_MESSAGE__FK_CHAT);
    }

    private transient FxMessage _fxMessage;
    private transient FxUser _fxUser;
    private transient FxChat _fxChat;

    /**
     * Get the implicit join path to the <code>public.fx_message</code> table.
     */
    public FxMessage fxMessage() {
        if (_fxMessage == null)
            _fxMessage = new FxMessage(this, Keys.FX_MESSAGE__FK_PARENT);

        return _fxMessage;
    }

    /**
     * Get the implicit join path to the <code>public.fx_user</code> table.
     */
    public FxUser fxUser() {
        if (_fxUser == null)
            _fxUser = new FxUser(this, Keys.FX_MESSAGE__FK_SENDER);

        return _fxUser;
    }

    /**
     * Get the implicit join path to the <code>public.fx_chat</code> table.
     */
    public FxChat fxChat() {
        if (_fxChat == null)
            _fxChat = new FxChat(this, Keys.FX_MESSAGE__FK_CHAT);

        return _fxChat;
    }

    @Override
    public FxMessage as(String alias) {
        return new FxMessage(DSL.name(alias), this);
    }

    @Override
    public FxMessage as(Name alias) {
        return new FxMessage(alias, this);
    }

    @Override
    public FxMessage as(Table<?> alias) {
        return new FxMessage(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxMessage rename(String name) {
        return new FxMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxMessage rename(Name name) {
        return new FxMessage(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxMessage rename(Table<?> name) {
        return new FxMessage(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, OffsetDateTime, OffsetDateTime, OffsetDateTime, String, Long, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function8<? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function8<? super Long, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super Long, ? super Long, ? super Long, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
