/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxQuestionDraftRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function17;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row17;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxQuestionDraft extends TableImpl<FxQuestionDraftRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_question_draft</code>
     */
    public static final FxQuestionDraft FX_QUESTION_DRAFT = new FxQuestionDraft();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxQuestionDraftRecord> getRecordType() {
        return FxQuestionDraftRecord.class;
    }

    /**
     * The column <code>public.fx_question_draft.id</code>.
     */
    public final TableField<FxQuestionDraftRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_question_draft.key</code>.
     */
    public final TableField<FxQuestionDraftRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.created_at</code>.
     */
    public final TableField<FxQuestionDraftRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.updated_at</code>.
     */
    public final TableField<FxQuestionDraftRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.fk_test_draft_section</code>.
     */
    public final TableField<FxQuestionDraftRecord, Long> FK_TEST_DRAFT_SECTION = createField(DSL.name("fk_test_draft_section"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.position</code>.
     */
    public final TableField<FxQuestionDraftRecord, Integer> POSITION = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.required</code>.
     */
    public final TableField<FxQuestionDraftRecord, Boolean> REQUIRED = createField(DSL.name("required"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.type</code>.
     */
    public final TableField<FxQuestionDraftRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.allow_empty</code>.
     */
    public final TableField<FxQuestionDraftRecord, Boolean> ALLOW_EMPTY = createField(DSL.name("allow_empty"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.fx_question_draft.title</code>.
     */
    public final TableField<FxQuestionDraftRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_question_draft.description</code>.
     */
    public final TableField<FxQuestionDraftRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_question_draft.question</code>.
     */
    public final TableField<FxQuestionDraftRecord, String> QUESTION = createField(DSL.name("question"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.points</code>.
     */
    public final TableField<FxQuestionDraftRecord, Double> POINTS = createField(DSL.name("points"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>public.fx_question_draft.deduction_wrong_answer</code>.
     */
    public final TableField<FxQuestionDraftRecord, Double> DEDUCTION_WRONG_ANSWER = createField(DSL.name("deduction_wrong_answer"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.fx_question_draft.shown_answers</code>.
     */
    public final TableField<FxQuestionDraftRecord, Integer> SHOWN_ANSWERS = createField(DSL.name("shown_answers"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.fx_question_draft.shuffle_answers</code>.
     */
    public final TableField<FxQuestionDraftRecord, Boolean> SHUFFLE_ANSWERS = createField(DSL.name("shuffle_answers"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.fx_question_draft.review_manually</code>.
     */
    public final TableField<FxQuestionDraftRecord, Boolean> REVIEW_MANUALLY = createField(DSL.name("review_manually"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private FxQuestionDraft(Name alias, Table<FxQuestionDraftRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxQuestionDraft(Name alias, Table<FxQuestionDraftRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_question_draft</code> table reference
     */
    public FxQuestionDraft(String alias) {
        this(DSL.name(alias), FX_QUESTION_DRAFT);
    }

    /**
     * Create an aliased <code>public.fx_question_draft</code> table reference
     */
    public FxQuestionDraft(Name alias) {
        this(alias, FX_QUESTION_DRAFT);
    }

    /**
     * Create a <code>public.fx_question_draft</code> table reference
     */
    public FxQuestionDraft() {
        this(DSL.name("fx_question_draft"), null);
    }

    public <O extends Record> FxQuestionDraft(Table<O> child, ForeignKey<O, FxQuestionDraftRecord> key) {
        super(child, key, FX_QUESTION_DRAFT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxQuestionDraftRecord, Long> getIdentity() {
        return (Identity<FxQuestionDraftRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxQuestionDraftRecord> getPrimaryKey() {
        return Keys.FX_QUESTION_DRAFT_PKEY;
    }

    @Override
    public List<UniqueKey<FxQuestionDraftRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_QUESTION_DRAFT_KEY_KEY);
    }

    @Override
    public List<ForeignKey<FxQuestionDraftRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_QUESTION_DRAFT__FK_TEST_DRAFT_SECTION);
    }

    private transient FxTestSectionDraft _fxTestSectionDraft;

    /**
     * Get the implicit join path to the
     * <code>public.fx_test_section_draft</code> table.
     */
    public FxTestSectionDraft fxTestSectionDraft() {
        if (_fxTestSectionDraft == null)
            _fxTestSectionDraft = new FxTestSectionDraft(this, Keys.FX_QUESTION_DRAFT__FK_TEST_DRAFT_SECTION);

        return _fxTestSectionDraft;
    }

    @Override
    public FxQuestionDraft as(String alias) {
        return new FxQuestionDraft(DSL.name(alias), this);
    }

    @Override
    public FxQuestionDraft as(Name alias) {
        return new FxQuestionDraft(alias, this);
    }

    @Override
    public FxQuestionDraft as(Table<?> alias) {
        return new FxQuestionDraft(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxQuestionDraft rename(String name) {
        return new FxQuestionDraft(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxQuestionDraft rename(Name name) {
        return new FxQuestionDraft(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxQuestionDraft rename(Table<?> name) {
        return new FxQuestionDraft(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row17 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Integer, Boolean, String, Boolean, String, String, String, Double, Double, Integer, Boolean, Boolean> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function17<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super Integer, ? super Boolean, ? super String, ? super Boolean, ? super String, ? super String, ? super String, ? super Double, ? super Double, ? super Integer, ? super Boolean, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function17<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super Integer, ? super Boolean, ? super String, ? super Boolean, ? super String, ? super String, ? super String, ? super Double, ? super Double, ? super Integer, ? super Boolean, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
