/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxTestSectionDraftI18nRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestSectionDraftI18n extends TableImpl<FxTestSectionDraftI18nRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_test_section_draft_i18n</code>
     */
    public static final FxTestSectionDraftI18n FX_TEST_SECTION_DRAFT_I18N = new FxTestSectionDraftI18n();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxTestSectionDraftI18nRecord> getRecordType() {
        return FxTestSectionDraftI18nRecord.class;
    }

    /**
     * The column
     * <code>public.fx_test_section_draft_i18n.fk_test_draft_section</code>.
     */
    public final TableField<FxTestSectionDraftI18nRecord, Long> FK_TEST_DRAFT_SECTION = createField(DSL.name("fk_test_draft_section"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_draft_i18n.language</code>.
     */
    public final TableField<FxTestSectionDraftI18nRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_draft_i18n.created_at</code>.
     */
    public final TableField<FxTestSectionDraftI18nRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_draft_i18n.updated_at</code>.
     */
    public final TableField<FxTestSectionDraftI18nRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_draft_i18n.title</code>.
     */
    public final TableField<FxTestSectionDraftI18nRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_draft_i18n.description</code>.
     */
    public final TableField<FxTestSectionDraftI18nRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private FxTestSectionDraftI18n(Name alias, Table<FxTestSectionDraftI18nRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxTestSectionDraftI18n(Name alias, Table<FxTestSectionDraftI18nRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_test_section_draft_i18n</code> table
     * reference
     */
    public FxTestSectionDraftI18n(String alias) {
        this(DSL.name(alias), FX_TEST_SECTION_DRAFT_I18N);
    }

    /**
     * Create an aliased <code>public.fx_test_section_draft_i18n</code> table
     * reference
     */
    public FxTestSectionDraftI18n(Name alias) {
        this(alias, FX_TEST_SECTION_DRAFT_I18N);
    }

    /**
     * Create a <code>public.fx_test_section_draft_i18n</code> table reference
     */
    public FxTestSectionDraftI18n() {
        this(DSL.name("fx_test_section_draft_i18n"), null);
    }

    public <O extends Record> FxTestSectionDraftI18n(Table<O> child, ForeignKey<O, FxTestSectionDraftI18nRecord> key) {
        super(child, key, FX_TEST_SECTION_DRAFT_I18N);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FxTestSectionDraftI18nRecord> getPrimaryKey() {
        return Keys.PK_TEST_DRAFT_SECTION_I18N;
    }

    @Override
    public List<ForeignKey<FxTestSectionDraftI18nRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_TEST_SECTION_DRAFT_I18N__FK_TEST_DRAFT_SECTION);
    }

    private transient FxTestSectionDraft _fxTestSectionDraft;

    /**
     * Get the implicit join path to the
     * <code>public.fx_test_section_draft</code> table.
     */
    public FxTestSectionDraft fxTestSectionDraft() {
        if (_fxTestSectionDraft == null)
            _fxTestSectionDraft = new FxTestSectionDraft(this, Keys.FX_TEST_SECTION_DRAFT_I18N__FK_TEST_DRAFT_SECTION);

        return _fxTestSectionDraft;
    }

    @Override
    public FxTestSectionDraftI18n as(String alias) {
        return new FxTestSectionDraftI18n(DSL.name(alias), this);
    }

    @Override
    public FxTestSectionDraftI18n as(Name alias) {
        return new FxTestSectionDraftI18n(alias, this);
    }

    @Override
    public FxTestSectionDraftI18n as(Table<?> alias) {
        return new FxTestSectionDraftI18n(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestSectionDraftI18n rename(String name) {
        return new FxTestSectionDraftI18n(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestSectionDraftI18n rename(Name name) {
        return new FxTestSectionDraftI18n(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestSectionDraftI18n rename(Table<?> name) {
        return new FxTestSectionDraftI18n(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
