/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxTestDraftRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function18;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row18;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestDraft extends TableImpl<FxTestDraftRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_test_draft</code>
     */
    public static final FxTestDraft FX_TEST_DRAFT = new FxTestDraft();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxTestDraftRecord> getRecordType() {
        return FxTestDraftRecord.class;
    }

    /**
     * The column <code>public.fx_test_draft.id</code>.
     */
    public final TableField<FxTestDraftRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_test_draft.key</code>.
     */
    public final TableField<FxTestDraftRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.created_at</code>.
     */
    public final TableField<FxTestDraftRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.updated_at</code>.
     */
    public final TableField<FxTestDraftRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.deleted_at</code>.
     */
    public final TableField<FxTestDraftRecord, OffsetDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.fx_test_draft.archived_at</code>.
     */
    public final TableField<FxTestDraftRecord, OffsetDateTime> ARCHIVED_AT = createField(DSL.name("archived_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.fx_test_draft.published_at</code>.
     */
    public final TableField<FxTestDraftRecord, OffsetDateTime> PUBLISHED_AT = createField(DSL.name("published_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.fx_test_draft.published_version</code>.
     */
    public final TableField<FxTestDraftRecord, Long> PUBLISHED_VERSION = createField(DSL.name("published_version"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.fx_test_draft.status</code>.
     */
    public final TableField<FxTestDraftRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.title</code>.
     */
    public final TableField<FxTestDraftRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.description</code>.
     */
    public final TableField<FxTestDraftRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_test_draft.author</code>.
     */
    public final TableField<FxTestDraftRecord, String> AUTHOR = createField(DSL.name("author"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.fx_test_draft.execution_mode</code>.
     */
    public final TableField<FxTestDraftRecord, String> EXECUTION_MODE = createField(DSL.name("execution_mode"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.points_to_pass</code>.
     */
    public final TableField<FxTestDraftRecord, Double> POINTS_TO_PASS = createField(DSL.name("points_to_pass"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.fx_test_draft.percentage_to_pass</code>.
     */
    public final TableField<FxTestDraftRecord, Double> PERCENTAGE_TO_PASS = createField(DSL.name("percentage_to_pass"), SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>public.fx_test_draft.duration</code>.
     */
    public final TableField<FxTestDraftRecord, Integer> DURATION = createField(DSL.name("duration"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.fx_test_draft.shuffle_sections</code>.
     */
    public final TableField<FxTestDraftRecord, Boolean> SHUFFLE_SECTIONS = createField(DSL.name("shuffle_sections"), SQLDataType.BOOLEAN.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_draft.shuffle_questions</code>.
     */
    public final TableField<FxTestDraftRecord, Boolean> SHUFFLE_QUESTIONS = createField(DSL.name("shuffle_questions"), SQLDataType.BOOLEAN.nullable(false), this, "");

    private FxTestDraft(Name alias, Table<FxTestDraftRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxTestDraft(Name alias, Table<FxTestDraftRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_test_draft</code> table reference
     */
    public FxTestDraft(String alias) {
        this(DSL.name(alias), FX_TEST_DRAFT);
    }

    /**
     * Create an aliased <code>public.fx_test_draft</code> table reference
     */
    public FxTestDraft(Name alias) {
        this(alias, FX_TEST_DRAFT);
    }

    /**
     * Create a <code>public.fx_test_draft</code> table reference
     */
    public FxTestDraft() {
        this(DSL.name("fx_test_draft"), null);
    }

    public <O extends Record> FxTestDraft(Table<O> child, ForeignKey<O, FxTestDraftRecord> key) {
        super(child, key, FX_TEST_DRAFT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxTestDraftRecord, Long> getIdentity() {
        return (Identity<FxTestDraftRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxTestDraftRecord> getPrimaryKey() {
        return Keys.FX_TEST_DRAFT_PKEY;
    }

    @Override
    public List<UniqueKey<FxTestDraftRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_TEST_DRAFT_KEY_KEY);
    }

    @Override
    public FxTestDraft as(String alias) {
        return new FxTestDraft(DSL.name(alias), this);
    }

    @Override
    public FxTestDraft as(Name alias) {
        return new FxTestDraft(alias, this);
    }

    @Override
    public FxTestDraft as(Table<?> alias) {
        return new FxTestDraft(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestDraft rename(String name) {
        return new FxTestDraft(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestDraft rename(Name name) {
        return new FxTestDraft(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestDraft rename(Table<?> name) {
        return new FxTestDraft(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row18 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, UUID, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, OffsetDateTime, Long, String, String, String, String, String, Double, Double, Integer, Boolean, Boolean> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function18<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Double, ? super Double, ? super Integer, ? super Boolean, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function18<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super String, ? super String, ? super String, ? super String, ? super String, ? super Double, ? super Double, ? super Integer, ? super Boolean, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
