/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxTestExecutionAnswerRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function9;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row9;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestExecutionAnswer extends TableImpl<FxTestExecutionAnswerRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_test_execution_answer</code>
     */
    public static final FxTestExecutionAnswer FX_TEST_EXECUTION_ANSWER = new FxTestExecutionAnswer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxTestExecutionAnswerRecord> getRecordType() {
        return FxTestExecutionAnswerRecord.class;
    }

    /**
     * The column <code>public.fx_test_execution_answer.id</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_test_execution_answer.key</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_execution_answer.created_at</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_execution_answer.updated_at</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_execution_answer.fk_answer</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, Long> FK_ANSWER = createField(DSL.name("fk_answer"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>public.fx_test_execution_answer.fk_test_execution_question</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, Long> FK_TEST_EXECUTION_QUESTION = createField(DSL.name("fk_test_execution_question"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_execution_answer.position</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, Integer> POSITION = createField(DSL.name("position"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_execution_answer.selected</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, Boolean> SELECTED = createField(DSL.name("selected"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.fx_test_execution_answer.content</code>.
     */
    public final TableField<FxTestExecutionAnswerRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    private FxTestExecutionAnswer(Name alias, Table<FxTestExecutionAnswerRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxTestExecutionAnswer(Name alias, Table<FxTestExecutionAnswerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_test_execution_answer</code> table
     * reference
     */
    public FxTestExecutionAnswer(String alias) {
        this(DSL.name(alias), FX_TEST_EXECUTION_ANSWER);
    }

    /**
     * Create an aliased <code>public.fx_test_execution_answer</code> table
     * reference
     */
    public FxTestExecutionAnswer(Name alias) {
        this(alias, FX_TEST_EXECUTION_ANSWER);
    }

    /**
     * Create a <code>public.fx_test_execution_answer</code> table reference
     */
    public FxTestExecutionAnswer() {
        this(DSL.name("fx_test_execution_answer"), null);
    }

    public <O extends Record> FxTestExecutionAnswer(Table<O> child, ForeignKey<O, FxTestExecutionAnswerRecord> key) {
        super(child, key, FX_TEST_EXECUTION_ANSWER);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxTestExecutionAnswerRecord, Long> getIdentity() {
        return (Identity<FxTestExecutionAnswerRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxTestExecutionAnswerRecord> getPrimaryKey() {
        return Keys.FX_TEST_EXECUTION_ANSWER_PKEY;
    }

    @Override
    public List<UniqueKey<FxTestExecutionAnswerRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_TEST_EXECUTION_ANSWER_KEY_KEY);
    }

    @Override
    public List<ForeignKey<FxTestExecutionAnswerRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_TEST_EXECUTION_ANSWER__FK_ANSWER, Keys.FX_TEST_EXECUTION_ANSWER__FK_TEST_EXECUTION_QUESTION);
    }

    private transient FxAnswer _fxAnswer;
    private transient FxTestExecutionQuestion _fxTestExecutionQuestion;

    /**
     * Get the implicit join path to the <code>public.fx_answer</code> table.
     */
    public FxAnswer fxAnswer() {
        if (_fxAnswer == null)
            _fxAnswer = new FxAnswer(this, Keys.FX_TEST_EXECUTION_ANSWER__FK_ANSWER);

        return _fxAnswer;
    }

    /**
     * Get the implicit join path to the
     * <code>public.fx_test_execution_question</code> table.
     */
    public FxTestExecutionQuestion fxTestExecutionQuestion() {
        if (_fxTestExecutionQuestion == null)
            _fxTestExecutionQuestion = new FxTestExecutionQuestion(this, Keys.FX_TEST_EXECUTION_ANSWER__FK_TEST_EXECUTION_QUESTION);

        return _fxTestExecutionQuestion;
    }

    @Override
    public FxTestExecutionAnswer as(String alias) {
        return new FxTestExecutionAnswer(DSL.name(alias), this);
    }

    @Override
    public FxTestExecutionAnswer as(Name alias) {
        return new FxTestExecutionAnswer(alias, this);
    }

    @Override
    public FxTestExecutionAnswer as(Table<?> alias) {
        return new FxTestExecutionAnswer(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestExecutionAnswer rename(String name) {
        return new FxTestExecutionAnswer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestExecutionAnswer rename(Name name) {
        return new FxTestExecutionAnswer(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestExecutionAnswer rename(Table<?> name) {
        return new FxTestExecutionAnswer(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row9 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, UUID, OffsetDateTime, OffsetDateTime, Long, Long, Integer, Boolean, String> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function9<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super Long, ? super Integer, ? super Boolean, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function9<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super Long, ? super Long, ? super Integer, ? super Boolean, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
