/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxTestSectionI18nRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxTestSectionI18n extends TableImpl<FxTestSectionI18nRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_test_section_i18n</code>
     */
    public static final FxTestSectionI18n FX_TEST_SECTION_I18N = new FxTestSectionI18n();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxTestSectionI18nRecord> getRecordType() {
        return FxTestSectionI18nRecord.class;
    }

    /**
     * The column <code>public.fx_test_section_i18n.fk_test_section</code>.
     */
    public final TableField<FxTestSectionI18nRecord, Long> FK_TEST_SECTION = createField(DSL.name("fk_test_section"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_i18n.language</code>.
     */
    public final TableField<FxTestSectionI18nRecord, String> LANGUAGE = createField(DSL.name("language"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_i18n.created_at</code>.
     */
    public final TableField<FxTestSectionI18nRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_i18n.updated_at</code>.
     */
    public final TableField<FxTestSectionI18nRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_i18n.title</code>.
     */
    public final TableField<FxTestSectionI18nRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_test_section_i18n.description</code>.
     */
    public final TableField<FxTestSectionI18nRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private FxTestSectionI18n(Name alias, Table<FxTestSectionI18nRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxTestSectionI18n(Name alias, Table<FxTestSectionI18nRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_test_section_i18n</code> table
     * reference
     */
    public FxTestSectionI18n(String alias) {
        this(DSL.name(alias), FX_TEST_SECTION_I18N);
    }

    /**
     * Create an aliased <code>public.fx_test_section_i18n</code> table
     * reference
     */
    public FxTestSectionI18n(Name alias) {
        this(alias, FX_TEST_SECTION_I18N);
    }

    /**
     * Create a <code>public.fx_test_section_i18n</code> table reference
     */
    public FxTestSectionI18n() {
        this(DSL.name("fx_test_section_i18n"), null);
    }

    public <O extends Record> FxTestSectionI18n(Table<O> child, ForeignKey<O, FxTestSectionI18nRecord> key) {
        super(child, key, FX_TEST_SECTION_I18N);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<FxTestSectionI18nRecord> getPrimaryKey() {
        return Keys.PK_TEST_SECTION_I18N;
    }

    @Override
    public List<ForeignKey<FxTestSectionI18nRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FX_TEST_SECTION_I18N__FK_TEST_SECTION);
    }

    private transient FxTestSection _fxTestSection;

    /**
     * Get the implicit join path to the <code>public.fx_test_section</code>
     * table.
     */
    public FxTestSection fxTestSection() {
        if (_fxTestSection == null)
            _fxTestSection = new FxTestSection(this, Keys.FX_TEST_SECTION_I18N__FK_TEST_SECTION);

        return _fxTestSection;
    }

    @Override
    public FxTestSectionI18n as(String alias) {
        return new FxTestSectionI18n(DSL.name(alias), this);
    }

    @Override
    public FxTestSectionI18n as(Name alias) {
        return new FxTestSectionI18n(alias, this);
    }

    @Override
    public FxTestSectionI18n as(Table<?> alias) {
        return new FxTestSectionI18n(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestSectionI18n rename(String name) {
        return new FxTestSectionI18n(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestSectionI18n rename(Name name) {
        return new FxTestSectionI18n(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxTestSectionI18n rename(Table<?> name) {
        return new FxTestSectionI18n(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, OffsetDateTime, OffsetDateTime, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super String, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super String, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
