/*
 * This file is generated by jOOQ.
 */
package com.famulex.api.jooq.tables;


import com.famulex.api.jooq.Keys;
import com.famulex.api.jooq.Public;
import com.famulex.api.jooq.tables.records.FxUpgradeRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FxUpgrade extends TableImpl<FxUpgradeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.fx_upgrade</code>
     */
    public static final FxUpgrade FX_UPGRADE = new FxUpgrade();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FxUpgradeRecord> getRecordType() {
        return FxUpgradeRecord.class;
    }

    /**
     * The column <code>public.fx_upgrade.id</code>.
     */
    public final TableField<FxUpgradeRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.fx_upgrade.key</code>.
     */
    public final TableField<FxUpgradeRecord, UUID> KEY = createField(DSL.name("key"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.fx_upgrade.created_at</code>.
     */
    public final TableField<FxUpgradeRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_upgrade.updated_at</code>.
     */
    public final TableField<FxUpgradeRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.fx_upgrade.version</code>.
     */
    public final TableField<FxUpgradeRecord, String> VERSION = createField(DSL.name("version"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.fx_upgrade.executed_successfully</code>.
     */
    public final TableField<FxUpgradeRecord, Boolean> EXECUTED_SUCCESSFULLY = createField(DSL.name("executed_successfully"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private FxUpgrade(Name alias, Table<FxUpgradeRecord> aliased) {
        this(alias, aliased, null);
    }

    private FxUpgrade(Name alias, Table<FxUpgradeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>public.fx_upgrade</code> table reference
     */
    public FxUpgrade(String alias) {
        this(DSL.name(alias), FX_UPGRADE);
    }

    /**
     * Create an aliased <code>public.fx_upgrade</code> table reference
     */
    public FxUpgrade(Name alias) {
        this(alias, FX_UPGRADE);
    }

    /**
     * Create a <code>public.fx_upgrade</code> table reference
     */
    public FxUpgrade() {
        this(DSL.name("fx_upgrade"), null);
    }

    public <O extends Record> FxUpgrade(Table<O> child, ForeignKey<O, FxUpgradeRecord> key) {
        super(child, key, FX_UPGRADE);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<FxUpgradeRecord, Long> getIdentity() {
        return (Identity<FxUpgradeRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FxUpgradeRecord> getPrimaryKey() {
        return Keys.FX_UPGRADE_PKEY;
    }

    @Override
    public List<UniqueKey<FxUpgradeRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.FX_UPGRADE_KEY_KEY);
    }

    @Override
    public FxUpgrade as(String alias) {
        return new FxUpgrade(DSL.name(alias), this);
    }

    @Override
    public FxUpgrade as(Name alias) {
        return new FxUpgrade(alias, this);
    }

    @Override
    public FxUpgrade as(Table<?> alias) {
        return new FxUpgrade(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public FxUpgrade rename(String name) {
        return new FxUpgrade(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxUpgrade rename(Name name) {
        return new FxUpgrade(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public FxUpgrade rename(Table<?> name) {
        return new FxUpgrade(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, UUID, OffsetDateTime, OffsetDateTime, String, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Long, ? super UUID, ? super OffsetDateTime, ? super OffsetDateTime, ? super String, ? super Boolean, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
