url=jdbc:postgresql://localhost:10000/famulex
username=famulex
password=famulex
classpath=$projectDir/src/main/resources/
outputChangeLogFile=db/generated/changelog.xml
changeLogFile=db/db.changelog-master.xml
