name: Build Image - Latest

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FONTAWESOME_NPM_TOKEN: ${{ secrets.FONTAWESOME_NPM_TOKEN }}
  CODUCTION_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-test-publish:
    name: Test, Build, Deploy Latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"
      - uses: actions/cache@v3
        name: Setup NPM cache
        with:
          path: "node_modules"
          key: ${{ runner.os }}-npm-store-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-store
      - uses: actions/cache@v3
        name: Setup Nx cache
        with:
          path: node_modules/.cache/nx
          key: ${{ runner.os }}-nx-cache
          restore-keys: ${{ runner.os }}-nx-cache
      - uses: actions/cache@v3
        name: Setup Cypress cache
        with:
          path: /home/runner/.cache/Cypress
          key: ${{ runner.os }}-cypress-cache
          restore-keys: ${{ runner.os }}-cypress-cache
      - name: Install dependencies
        run: npm install --force
      - uses: nrwl/nx-set-shas@v3
      - run: npx nx affected -t lint
      - run: npx nx affected -t test --configuration=ci
      # - run: npx nx affected -t e2e --configuration=ci
      - run: npx nx affected -t build --configuration=ci
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Image SHA
        run: echo "IMAGE_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - run: npx nx affected -t build-image --configuration=ci
        env:
          # For Nx-Container actions
          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_PUSH: true
          # For Maven actions
          REGISTRY_USER: ${{ github.actor }}
          REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Testing Instance
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.CODUCTION_TESTING_HOST }}
          username: ${{ vars.CODUCTION_TESTING_USER }}
          key: ${{ secrets.CODUCTION_TESTING_SSH_KEY }}
          passphrase: ${{ secrets.CODUCTION_TESTING_SSH_KEY_PASS }}
          script: /home/${{ vars.CODUCTION_TESTING_USER }}/scripts/deploy/famulex-latest.sh
